// layer.mjs's types: the reader's entry, what Plan 8d imports
export { parseLayout, indexLayout, LAYOUT, LAYOUT_CAP, LAYOUT_VALUES, LayoutRefusal } from '../layout/file.mjs'
export { layerRulesFor } from '../layer-rules.mjs'
export { rolesFor, familyOfFonts, FACES } from '../font-roles.mjs'
export { loadHyphenator } from './hyphen.mjs'
export { trText, trPiecesOf, kOfSource, LAYER_COLOURS } from './pieces.mjs'
export { layUnit } from './fit.mjs'
export { bodyUnits, evenOf } from './page.mjs'
export { checkPieces } from './net.mjs'
export { drawUnit, spansOf, unitAt } from './draw.mjs'
export { swapMasks } from './swap.mjs'
// the types the reader names (no value)
export type { LayoutFile, LayoutIndex, LayoutUnit } from '../layout/file.mjs'
export type { LayerRules } from '../layer-rules.mjs'
export type { EnglishFamily, Face, FaceId, RoleSet } from '../font-roles.mjs'
export type { Hyphenator } from './hyphen.mjs'
export type { TrPiece } from './pieces.mjs'
export type { Measure, TextIn } from './tokens.mjs'
export type { FitState, LaidItem, LaidLine, LaidUnit, Laid, LayerInput, Tr, Unfit } from './fit.mjs'
export type { DrawLine, DrawRun, RemovedPage, UnitDraw } from './draw.mjs'
