#!/usr/bin/env bash
# One-line install of the recognition helper (macOS), the command the popup copies:
#   curl -fsSL https://raw.githubusercontent.com/SRjoeee/ReadarXiv/<ref>/helper/install-remote.sh | bash -s -- <extension-id> [<ref>]
# <ref> is where the sources come from: the commit the extension was built from (the popup passes it, issue #158) or
# a branch name, a release tag (v0.4.0) or a commit (default main). AXT_HELPER_DRY_RUN=1 prints the tarball URL and stops, for the tests.
# Downloads this repository's helper/ into ~/Library/Application Support/Readarxiv/helper, builds it
# with the Swift toolchain of the Xcode Command Line Tools, and registers the Native Messaging host
# for Chrome and Chromium through register.sh, the one writer of the manifest (DESIGN §15.4). Re-running
# updates in place. No sudo, nothing outside that directory and the two NativeMessagingHosts folders.
set -euo pipefail

REPO=SRjoeee/ReadarXiv
REF="${2:-${AXT_HELPER_REF:-main}}"
DIR="$HOME/Library/Application Support/Readarxiv/helper"

id="${1:-}"
if [ -z "$id" ]; then
  echo "Usage: curl -fsSL https://raw.githubusercontent.com/$REPO/$REF/helper/install-remote.sh | bash -s -- <extension id> [branch]" >&2
  echo "Extension id: the install command copied from the popup carries it; or open chrome://extensions in developer mode to read it." >&2
  exit 2
fi
if ! [[ "$id" =~ ^[a-p]{32}$ ]]; then
  echo "Not a valid extension id: $id (expected 32 lowercase letters a–p)" >&2
  exit 2
fi
# A 40-digit hash is a commit; `v` and a digit is a release tag; anything else a branch. codeload serves a commit at its
# bare path, a tag under refs/tags, a branch under refs/heads. A branch that happens to be named like a hash or a tag is
# tried second, under refs/heads (Devin on #214)
BRANCH_TARBALL="https://codeload.github.com/$REPO/tar.gz/refs/heads/$REF"
if [[ "$REF" =~ ^[0-9a-f]{40}$ ]]; then TARBALL="https://codeload.github.com/$REPO/tar.gz/$REF"
elif [[ "$REF" =~ ^v[0-9] ]]; then TARBALL="https://codeload.github.com/$REPO/tar.gz/refs/tags/$REF"
else TARBALL="$BRANCH_TARBALL"; fi
if [ "${AXT_HELPER_DRY_RUN:-}" = "1" ]; then
  echo "$TARBALL"
  exit 0
fi
if [ "$(uname -s)" != "Darwin" ]; then
  echo "The recognition helper supports macOS only for now." >&2
  exit 1
fi
if ! xcode-select -p >/dev/null 2>&1; then
  echo "Xcode Command Line Tools are required. Run xcode-select --install first, then run this command again." >&2
  exit 1
fi

echo "Downloading the helper sources to $DIR …"
mkdir -p "$DIR"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -fsSL "$TARBALL" -o "$tmp/src.tgz" || { [ "$TARBALL" != "$BRANCH_TARBALL" ] && curl -fsSL "$BRANCH_TARBALL" -o "$tmp/src.tgz"; }
tar -xzf "$tmp/src.tgz" -C "$tmp"
# The directory name is generated by GitHub from the **current** repository name (`<repo>-<ref>`), so it must not be hard-coded: once the
# repository is renamed a hard-coded glob never matches again, and the script would silently cp from an empty path on the next line (measured 2026-09-12:
# after the rename to Readarxiv the tarball unpacked to `Readarxiv-main/` while this looked for
# `ArxivTranslate-*`, and the one-click install broke whole). The tarball has a single top-level directory; take it
src="$(find "$tmp" -maxdepth 1 -mindepth 1 -type d | head -1)"
[ -n "$src" ] || { echo "No source directory found after unpacking" >&2; exit 1; }
# Only what the build needs. `Tests` is removed and not copied: it holds the smoke test's images, which the package
# does not build — and earlier versions of this script put a paper's figure on every reader's machine with it
rm -rf "$DIR/Sources" "$DIR/Tests"
cp -R "$src/helper/Sources" "$src/helper/Package.swift" "$src/helper/LICENSE-macos-vision-ocr.txt" "$src/helper/register.sh" "$DIR/"

echo "Building (about a minute the first time) …"
(cd "$DIR" && swift build -c release >/dev/null)
BIN="$DIR/.build/release/axt-helper"
bash "$DIR/register.sh" "$BIN" "$id"

echo "Installed: $("$BIN" --version)"
echo "Image translation is available now; no need to reload the extension."
