#!/usr/bin/env bash
# One-line install of the recognition helper (macOS), the command the popup copies:
#   curl -fsSL https://raw.githubusercontent.com/SRjoeee/ReadarXiv/<ref>/helper/install-remote.sh | bash -s -- <extension-id> [<ref>]
# <ref> is the branch the sources come from (default main; the popup passes the one it was built from).
# Downloads this repository's helper/ into ~/Library/Application Support/Readarxiv/helper, builds it
# with the Swift toolchain of the Xcode Command Line Tools, and registers the Native Messaging host
# for Chrome and Chromium (DESIGN §15.4). Re-running updates in place. No sudo, nothing outside
# that directory and the two NativeMessagingHosts folders.
set -euo pipefail

REPO=SRjoeee/ReadarXiv
REF="${2:-${AXT_HELPER_REF:-main}}"
NAME=io.github.srjoeee.arxivtranslate
DIR="$HOME/Library/Application Support/Readarxiv/helper"

id="${1:-}"
if [ -z "$id" ]; then
  echo "Usage: curl -fsSL https://raw.githubusercontent.com/$REPO/$REF/helper/install-remote.sh | bash -s -- <extension id> [branch]" >&2
  echo "Extension id: the install command copied from the popup carries it; or open chrome://extensions in developer mode to read it." >&2
  exit 2
fi
if ! [[ "$id" =~ ^[a-p]{32}$ ]]; then
  echo "Not a valid extension id: $id (expected 32 lowercase letters a–p)" >&2
  exit 2
fi
if [ "$(uname -s)" != "Darwin" ]; then
  echo "The recognition helper supports macOS only for now." >&2
  exit 1
fi
if ! xcode-select -p >/dev/null 2>&1; then
  echo "Xcode Command Line Tools are required. Run xcode-select --install first, then run this command again." >&2
  exit 1
fi

echo "Downloading the helper sources to $DIR …"
mkdir -p "$DIR"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -fsSL "https://codeload.github.com/$REPO/tar.gz/refs/heads/$REF" -o "$tmp/src.tgz"
tar -xzf "$tmp/src.tgz" -C "$tmp"
# The directory name is generated by GitHub from the **current** repository name (`<repo>-<ref>`), so it must not be hard-coded: once the
# repository is renamed a hard-coded glob never matches again, and the script would silently cp from an empty path on the next line (measured 2026-09-12:
# after the rename to Readarxiv the tarball unpacked to `Readarxiv-main/` while this looked for
# `ArxivTranslate-*`, and the one-click install broke whole). The tarball has a single top-level directory; take it
src="$(find "$tmp" -maxdepth 1 -mindepth 1 -type d | head -1)"
[ -n "$src" ] || { echo "No source directory found after unpacking" >&2; exit 1; }
rm -rf "$DIR/Sources" "$DIR/Tests"
cp -R "$src/helper/Sources" "$src/helper/Package.swift" "$src/helper/LICENSE-macos-vision-ocr.txt" "$DIR/"
[ -d "$src/helper/Tests" ] && cp -R "$src/helper/Tests" "$DIR/"

echo "Building (about a minute the first time) …"
(cd "$DIR" && swift build -c release >/dev/null)
BIN="$DIR/.build/release/axt-helper"

for dir in "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts" \
           "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"; do
  mkdir -p "$dir"
  manifest="$dir/$NAME.json"
  # Keep the ids an earlier run allowed (another profile, a dev build): union, not overwrite
  origins="\"chrome-extension://$id/\""
  if [ -f "$manifest" ]; then
    while read -r existing; do
      [ -n "$existing" ] && [ "$existing" != "chrome-extension://$id/" ] && origins="$origins, \"$existing\""
    done < <(grep -o 'chrome-extension://[a-p]\{32\}/' "$manifest" | sort -u)
  fi
  cat > "$manifest" <<JSON
{
  "name": "$NAME",
  "description": "The image recognition helper of Readarxiv (Apple Vision)",
  "path": "$BIN",
  "type": "stdio",
  "allowed_origins": [$origins]
}
JSON
done

echo "Installed: $("$BIN" --version)"
echo "Image translation is available now; no need to reload the extension."
