// What each argument of a command or environment is: text, typeset content, a dimension, keys, a name, a register,
// code. One table for every reader of a paper's source (the front end's arity, the layout maker's classes, the layer's
// source fallback): LaTeXML's prototypes (latexml-args.mjs, generated by scripts/latexml-args.mjs), with the commands
// below written out by hand where LaTeXML leaves an argument untyped, reads its arguments in code, or has no binding.
//
// A command's parameters are a string of pairs, shape then role:
//   shapes  `{` a brace group or one token, as TeX takes an undelimited argument; `[` an optional argument in brackets;
//           `*` an optional star; `?` an optional `=`; `=` a literal `=` TeX skips; `_` TeX's own syntax for the role (a
//           number, a dimension, glue with plus and minus, one token or a group); `u` tokens up to a delimiter the
//           table does not name (read as not known); `b` tokens up to a brace (\def's parameter text)
//   roles   `t` text, `c` typeset content (a box's, a branch's), `a` an argument LaTeXML leaves untyped (text or a name),
//           `d` a dimension, glue or number, `k` keys and values, `n` a name (a label, a file, a colour, a counter),
//           `v` a name set as it is written (a URL, an e-mail address), `r` a register or a control sequence, `x` code (a
//           definition's body, tokens never typeset as they stand), `m` math, `s` a literal
// A register (\tabcolsep) is '=': TeX's assignment may follow it, `\tabcolsep=2pt`
import { BINDINGS, COMMANDS, ENVIRONMENTS, FRONT, LATEXML_COMMIT, PACKAGE_COMMANDS, PACKAGE_ENVIRONMENTS, REQUIRES } from './latexml-args.mjs'

export { LATEXML_COMMIT }
/** the roles' names, by their letter */
export const ROLES = Object.freeze({ t: 'text', c: 'content', a: 'arg', d: 'dimension', k: 'keys', n: 'name', v: 'verbatim', r: 'register', x: 'code', m: 'math', s: 'literal' })
/** roles whose argument a page may show as letters: what a source fallback draws (textArgsOf) — a name is no such one,
 *  though some commands set ink by one (an image's file, a counter's number): textless reads it as it may be */
const MAY_BE_TEXT = new Set(['t', 'c', 'a', 'v', 'm'])

/**
 * Commands as the front end reads them where LaTeXML's form says less than the paper's command takes, or nothing: an
 * argument it leaves untyped that is a name or a dimension (\setcounter{}{Number}'s counter, \vspace{}'s length), one
 * that is the text a box or a branch sets, a form it reads in code (\makebox, \resizebox, \captionof, \multicolumn),
 * and a few it has no binding for. Checked by hand against the packages' documentation and source (latex.ltx, graphicx,
 * xcolor, hyperref, booktabs, caption, multirow, makecell, adjustbox, enumitem, url). Not tabu's environment, whose
 * `to <width>` before its columns no parameter here reads
 */
const CURATED = {
  // boxes and colours: the last argument the text they set
  mbox: '{c', makebox: '[d[n{c', framebox: '[d[n{c', fbox: '{c', parbox: '[n[d[n{d{c', raisebox: '{d[d[d{c',
  resizebox: '*s{d{d{c', scalebox: '{d[d{c', rotatebox: '[k{d{c', reflectbox: '{c', colorbox: '[n{n{c', fcolorbox: '[n{n{n{c',
  textcolor: '[n{n{c', color: '[n{n', adjustbox: '{k{c', smash: '[n{c', phantom: '{x', hphantom: '{x', vphantom: '{x',
  // space, rules and the rows of a table
  vspace: '*s{d', hspace: '*s{d', addvspace: '{d', rule: '[d{d{d', specialrule: '{d{d{d', addlinespace: '[d', toprule: '[d',
  midrule: '[d', bottomrule: '[d', cline: '{n', hhline: '{n', noalign: '{x', tabularnewline: '[d', linespread: '{d', fontsize: '{d{d',
  enlargethispage: '*s{d', pagebreak: '[d', linebreak: '[d', nopagebreak: '[d', nolinebreak: '[d', multicolumn: '{d{n{c',
  multirow: '[n{d[d{d[d{c', makecell: '[n{c', shortstack: '[n{c',
  // lengths, counters and the paper's settings
  setlength: '{r{d', addtolength: '{r{d', settowidth: '{r{x', settoheight: '{r{x', settodepth: '{r{x', setcounter: '{n{d',
  addtocounter: '{n{d', stepcounter: '{n', refstepcounter: '{n', value: '{n', arabic: '{n', roman: '{n', Roman: '{n', alph: '{n',
  Alph: '{n', fnsymbol: '{n', numberwithin: '[n{n{n', theoremstyle: '{n', pagestyle: '{n', thispagestyle: '{n', pagenumbering: '{n',
  fontfamily: '{n', fontseries: '{n', fontshape: '{n', usefont: '{n{n{n{n', definecolor: '[n{n{n{k', colorlet: '[n{n[n{k',
  usepackage: '[k{n[n', RequirePackage: '[k{n[n', documentclass: '[k{n[n', graphicspath: '{n', bibliographystyle: '{n',
  bibliography: '{n', addbibresource: '[k{n', hypersetup: '{k', captionsetup: '[n{k', setlist: '[n{k', sisetup: '{k',
  lstset: '{k', tcbset: '{k', tikzset: '{k', pgfplotsset: '{k', geometry: '{k', setstretch: '{d',
  // references, links, files: their names stay; a link's text is text
  label: '{n', ref: '*s{n', eqref: '{n', pageref: '*s{n', autoref: '*s{n', cref: '*s{n', Cref: '*s{n', nameref: '*s{n',
  hyperref: '[n{t', hyperlink: '{n{t', hypertarget: '{n{t', href: '[k{n{t', url: '{v', nolinkurl: '{v', includegraphics: '*s[k[k{n',
  IfFileExists: '{n{c{c', InputIfFileExists: '{n{c{c', email: '[n{v', orcid: '[n{v', orcidlink: '{n', thanksref: '{n', inst: '{v',
  // definitions: a name, an arity, a default and a body, none of them typeset where they stand
  newcommand: '*s{r[d[x{x', renewcommand: '*s{r[d[x{x', providecommand: '*s{r[d[x{x', DeclareRobustCommand: '*s{r[d[x{x',
  newenvironment: '*s{n[d[x{x{x', renewenvironment: '*s{n[d[x{x{x', newtheorem: '*s{n[n{n[n', newcolumntype: '{n[d[x{x',
  DeclareMathOperator: '*s{r{x', newlength: '{r', newcounter: '{n[n', newif: '_r', let: '_r?s_r', def: '_rb{x', gdef: '_rb{x',
  edef: '_rb{x', xdef: '_rb{x',
  // text the reader sees, set apart: a caption outside a float (caption's \captionof), a deluxetable's
  captionof: '*s{n[t{t', tablecaption: '{t', markboth: '{t{t', markright: '{t',
}
/** environments as the front end reads them, where LaTeXML's form is missing or says less: a table's position and
 *  columns (its cells are walked), a box's width, a list's options (enumitem's keys), a theorem's title */
const CURATED_ENVS = {
  tabular: '[n{n', 'tabular*': '{d[n{n', tabularx: '{d[n{n', tabulary: '{d[n{n', longtable: '[n{n', supertabular: '{n',
  xtabular: '[n{n', array: '[n{n', minipage: '[n[d[n{d', multicols: '{d[c[d', 'multicols*': '{d[c[d', wrapfigure: '[d{n[d{d',
  wraptable: '[d{n[d{d', subfigure: '[n{d', subtable: '[n{d', adjustbox: '{k', tcolorbox: '[k', mdframed: '[k', enumerate: '[k',
  itemize: '[k', description: '[k', spacing: '{d', figure: '[n', 'figure*': '[n', table: '[n', 'table*': '[n', proof: '[t',
  thebibliography: '{n',
}

const parse = spec => (spec.match(/../g) ?? []).map(p => ({ shape: p[0], role: p[1] }))
/** parameters written as the table writes them (`[t`, `*s{n[t{t`): for a definition of the paper's own */
export const paramsOf = spec => Object.freeze(parse(spec))
const REGISTER = Object.freeze([{ shape: '=', role: 'r' }])
const known = spec => typeof spec === 'string' && spec !== '?' && !spec.includes('u')
const asParams = spec => (spec === '=' ? REGISTER : parse(spec))
const BINDING_INDEX = new Map(BINDINGS.map((b, k) => [b, k]))
/**
 * The LaTeXML bindings a paper has: its class and packages as its files name them (\documentclass, \LoadClass,
 * \usepackage, \RequirePackage, comments left out), with those their bindings load in turn. A class LaTeXML has no
 * binding for is read as the longest one whose name begins its name (revtex4-2 as revtex4), as LaTeXML reads it. A
 * Set of BINDINGS' indices, for commandParams
 */
export function bindingsOf(texts) {
  const out = new Set(), queue = []
  const add = k => { if (k !== undefined && !out.has(k)) { out.add(k); queue.push(k) } }
  for (const t of texts) {
    const text = t.replace(/(^|[^\\])%.*$/gm, '$1')
    for (const m of text.matchAll(/\\(documentclass|LoadClass(?:WithOptions)?|usepackage|RequirePackage(?:WithOptions)?)\s*(?:\[[^\]]*\]\s*)?\{([^}]*)\}/g)) {
      const cls = /class/i.test(m[1])
      for (const raw of m[2].split(',')) {
        const name = raw.trim()
        if (!name) continue
        const own = BINDING_INDEX.get(`${name}.${cls ? 'cls' : 'sty'}`)
        if (own !== undefined || !cls) { add(own); continue }
        let best = null
        for (const b of BINDINGS) if (b.endsWith('.cls') && name.startsWith(b.slice(0, -4)) && (!best || b.length > best.length)) best = b
        if (best) add(BINDING_INDEX.get(best))
      }
    }
  }
  while (queue.length) for (const r of REQUIRES[queue.pop()] ?? []) add(r)
  return out
}
/** a name's parameters by the forms LaTeXML gives it: where a paper's bindings (`bindings`) define it, theirs, and none
 *  where they differ; else the engine pools'; else, with no paper to tell (null), the one form every binding agrees on */
const byForms = (pools, packages, name, bindings) => {
  const pkg = packages[name]
  if (bindings && pkg) {
    const mine = pkg.filter(([, ...bs]) => bs.some(b => bindings.has(b))).map(([s]) => s)
    if (mine.length) return mine.length === 1 ? asParams(mine[0]) : null
  }
  if (pools[name] !== undefined) return known(pools[name]) ? asParams(pools[name]) : null
  return !bindings && pkg?.length === 1 ? asParams(pkg[0][0]) : null
}
/** a command's parameters ({ shape, role } each, by the letters above), or null where the table does not know them: as
 *  written out here, else by LaTeXML's forms for the paper's bindings (bindingsOf; null for none known) */
export function commandParams(name, bindings = null) {
  return known(CURATED[name]) ? asParams(CURATED[name]) : byForms(COMMANDS, PACKAGE_COMMANDS, name, bindings)
}
/** an environment's parameters after its \begin{name}, or null: as written out here, else LaTeXML's environment for the
 *  paper's bindings. Not a command of its name: LaTeX's \begin{x} runs \x, but a command LaTeXML knows by a name
 *  (amsmath's \boxed{…}) is no environment a paper defines by it (comment.sty's \specialcomment{boxed}) */
export function environmentParams(name, bindings = null) {
  return known(CURATED_ENVS[name]) ? asParams(CURATED_ENVS[name]) : byForms(ENVIRONMENTS, PACKAGE_ENVIRONMENTS, name, bindings)
}
/**
 * The front matter's commands, by what the front end makes of their text and which argument it is (1-based; 0 an
 * environment's body): `title`, `author` (names and places), `note`, `abstract`, `keywords`, `prose`. From LaTeXML's
 * hooks (\lx@add@affiliation, \lx@add@contact[role=dedicatory] …), less those whose argument names no text: a
 * copyright's kind (acmart's \setcopyright{acmlicensed}, a key the class tests), identifiers and numbers
 */
const NOT_FRONT_TEXT = new Set(['setcopyright', 'doi', 'acmDOI', 'acmISBN', 'ISSN', 'PII', 'arxivnumber', 'acmSubmissionID', 'acmArticle', 'acmArticleSeq', 'acmNumber', 'acmVolume', 'acmYear', 'acmMonth', 'acmPrice', 'volume', 'issue', 'pagerange', 'pubyear', 'microfiche', 'pacno', 'pacs', 'PACS', 'CRclass', 'ams', 'subclass'])
/** front matter LaTeXML has no binding for: AAAI's and MELBA's \affiliations{…} (aaai2026.sty, melba.cls), achemso's
 *  \alsoaffiliation[…]{…}, the keywords environment of the classes that have one */
const MORE_FRONT = { affiliations: ['author', 1], alsoaffiliation: ['author', 2], 'env:keywords': ['keywords', 0], 'env:IEEEkeywords': ['keywords', 0], 'env:abstract': ['abstract', 0] }
export const FRONT_ROLES = Object.freeze({ ...Object.fromEntries(Object.entries(FRONT).filter(([k]) => !NOT_FRONT_TEXT.has(k.replace(/^env:/, '')))), ...MORE_FRONT })

// ---------------------------------------------------------------- reading arguments as TeX takes them
const isLetter = c => (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c === '@'
/** spaces and tabs, and at most one line end: TeX lets an argument follow on the next line, but a blank line is \par;
 *  a comment goes with the line end it takes (latex-front.mjs skipSpaces) */
const skipSpaces = (s, i) => {
  let lines = 0, fresh = false
  while (i < s.length) {
    if (s[i] === ' ' || s[i] === '\t') i++
    else if (s[i] === '%') { const e = s.indexOf('\n', i); if (e < 0) return s.length; i = e + 1; fresh = true }
    else if (s[i] === '\n' && lines === 0 && !fresh) { lines++; i++; fresh = true }
    else break
  }
  return i
}
/** the end of a group opening at s[i], past its matching close; -1 where it does not close */
export function groupEnd(s, i, open = '{', close = '}') {
  let depth = 0
  for (let j = i; j < s.length; j++) {
    const c = s[j]
    if (c === '\\') { j++; continue }
    if (c === '%') { while (j < s.length && s[j] !== '\n') j++; continue }
    if (c === open) depth++
    else if (c === close && --depth === 0) return j + 1
  }
  return -1
}
/** one token at s[k]: a control sequence (its name, a starred one's star apart) or a character; its end */
const tokenEnd = (s, k) => {
  if (s[k] !== '\\') return k + 1
  let j = k + 1
  if (j < s.length && isLetter(s[j])) { while (j < s.length && isLetter(s[j])) j++; return j }
  return j + 1
}
// TeX's number and dimension: a sign, digits or a register, a unit; glue with its plus and minus
const UNIT = String.raw`(?:true\s*)?(?:pt|em|ex|cm|mm|in|bp|sp|pc|dd|cc|mu|px|fill?l?)(?![A-Za-z])`
const FACTOR = String.raw`[-+\s]*(?:\d+(?:[.,]\d*)?|[.,]\d+)?\s*`
const QUANTITY = String.raw`${FACTOR}(?:${UNIT}|\\[A-Za-z@]+(?:\s*\d+)?|\d*)`
const TEX_VALUE = new RegExp(String.raw`^\s*=?\s*(?:${QUANTITY})(?:\s*(?:plus|minus)\s*${QUANTITY})*`)
/**
 * The arguments of a command whose parameters the table knows, at s[i] just after its name: each { shape, role, param,
 * start, end } (`param` its parameter's index, a group's start at its brace or bracket), an optional one or a star only
 * where it is given; with where they
 * end, and `complete` false where a required one is missing or runs past `to` (a closing brace, the text's end): what
 * TeX would take is then not known, and the caller reads the command as it reads one it does not know
 */
export function readArgs(s, i, params, to = s.length) {
  const args = []
  let at = i
  for (const [param, { shape, role }] of params.entries()) {
    const k = skipSpaces(s, at)
    if (shape === '[') { if (s[k] === '[') { const e = groupEnd(s, k, '[', ']'); if (e < 0 || e > to) return { args, end: at, complete: false }; args.push({ shape, role, param, start: k, end: e }); at = e } continue }
    if (shape === '*') { if (s[k] === '*') { args.push({ shape, role, param, start: k, end: k + 1 }); at = k + 1 } continue }
    if (shape === '?' || shape === '=') { if (s[k] === '=') at = k + 1; continue }
    if (shape === '_' && role === 'd') {
      if (s[k] === '{') { const e = groupEnd(s, k); if (e < 0 || e > to) return { args, end: at, complete: false }; args.push({ shape, role, param, start: k, end: e }); at = e; continue }
      const m = TEX_VALUE.exec(s.slice(at, Math.min(to, at + 200)))
      if (m && /\S/.test(m[0])) { args.push({ shape, role, param, start: at, end: at + m[0].length }); at += m[0].length }
      continue
    }
    if (shape === 'b') { let e = at; while (e < to && s[e] !== '{' && s[e] !== '%') e++; if (e >= to || s[e] !== '{') return { args, end: at, complete: false }; if (e > at) args.push({ shape, role, param, start: at, end: e }); at = e; continue }
    if (shape !== '{' && shape !== '_') return { args, end: at, complete: false }
    // a bracket where a required argument is due is an optional one the table does not know of (a package's): not known
    if (k >= to || s[k] === '}' || s[k] === '[' || /\n[ \t]*\n/.test(s.slice(at, k + 1).replace(/%[^\n]*\n/g, ''))) return { args, end: at, complete: false }
    // a macro's parameter (#1, in a definition's body) is one token
    const e = s[k] === '{' ? groupEnd(s, k) : s[k] === '#' && /\d/.test(s[k + 1] ?? '') ? k + 2 : tokenEnd(s, k)
    if (e < 0 || e > to) return { args, end: at, complete: false }
    args.push({ shape, role, param, start: k, end: e })
    at = e
  }
  return { args, end: at, complete: true }
}

// ---------------------------------------------------------------- a placeholder's source
/** a command at s[i]: its name and where it ends (a starred one's star in the name's end, as the front end reads it) */
const commandAt = (s, i) => {
  let j = i + 1
  if (j < s.length && isLetter(s[j])) { while (j < s.length && isLetter(s[j])) j++; return { name: s.slice(i + 1, j), end: j } }
  return { name: s[j] ?? '', end: j + 1 }
}
/**
 * A placeholder's source as it would read without what is never text: each command the table knows keeps only its
 * arguments that may be typeset as text (text, content, and those LaTeXML leaves untyped), recursively; every other
 * argument goes — a dimension, keys, a name, a register, code. Commands the table does not know keep everything.
 * \specialrule{1pt}{-1pt}{0pt} and \rule[-1pt]{0pt}{2.2ex} become `\specialrule` and `\rule`, \raisebox{-1pt}{x}
 * `\raisebox{x}`, \multicolumn{2}{c}{x} `\multicolumn{x}`, \includegraphics[width=5cm]{{a.jpg}} `\includegraphics`:
 * a layer that draws a placeholder from its source draws its text alone (1706.03762's Table 2: "1pt-1pt0pt 0pt2.2ex"
 * drawn before a translated cell)
 */
export function textArgsOf(src) {
  let out = '', i = 0
  while (i < src.length) {
    const c = src[i]
    if (c === '%') { const e = src.indexOf('\n', i); i = e < 0 ? src.length : e + 1; continue }
    if (c === '{') { const e = groupEnd(src, i); if (e < 0) { out += c; i++; continue } out += `{${textArgsOf(src.slice(i + 1, e - 1))}}`; i = e; continue }
    if (c !== '\\') { out += c; i++; continue }
    const { name, end } = commandAt(src, i)
    const params = /^[A-Za-z@]+$/.test(name) ? commandParams(name) : null
    if (!params?.length) { out += src.slice(i, end); i = end; continue }
    const { args, end: e } = readArgs(src, end, params)
    out += src.slice(i, end)
    let kept = false
    for (const a of args) {
      if (!MAY_BE_TEXT.has(a.role)) continue
      const inner = src.slice(a.start, a.end)
      out += a.shape === '[' ? `[${textArgsOf(inner.slice(1, -1))}]` : inner.startsWith('{') ? `{${textArgsOf(inner.slice(1, -1))}}` : textArgsOf(inner)
      kept = true
    }
    // a control word whose arguments went keeps its end: a letter after it is no part of its name
    if (!kept && e > end && isLetter(src[e] ?? '')) out += ' '
    i = e
  }
  return out
}
/** roles whose argument no command sets as ink: a dimension, keys, code, a literal (and a register, given in a group) */
const INKLESS = new Set(['d', 'k', 'x', 's'])
/**
 * Whether a placeholder can never be a text rendering: its source one command the table knows, its arguments all
 * there and nothing after them, each a dimension, keys, code or a register — a rule, a space, a length set, a row's
 * spacing, a definition. What it sets, if anything (a rule's bar), is the page's own drawing, never letters. A name
 * may set ink (\\ref's number, \\inst's mark, an image), a bare token too (\\left's delimiter), and a command with no
 * parameter may set text (\\LaTeX, \\today): none of them is such a one
 */
export function textless(src) {
  const s = src.trim()
  if (!/^\\[A-Za-z@]+/.test(s)) return false
  const { name, end } = commandAt(s, 0)
  const params = commandParams(name)
  if (!params?.length || params === REGISTER) return false
  if (!params.every(p => INKLESS.has(p.role) || (p.role === 'r' && p.shape === '{')) || params.every(p => p.role === 's')) return false
  const { end: e, complete } = readArgs(s, end, params)
  return complete && !s.slice(e).trim()
}
