// Generated by scripts/caption-names.mjs: do not edit. From TeX Live's babel locale files (babel 26.12) in
// texlive/texlive:latest (sha256:7334b00bf8e7a0996f7ddd65482363aaf7711d372e569f3ea78509619e3083ff):
// the [captions] figure and table of the ini file the final imports for each target.
// The names a translated final gives its floats (\figurename, \tablename): the layer labels a float with them, as the
// final does, the number and the punctuation the original's (the table-groups brief, Problem 2).

/** by babel's tag: each float's name as babel's [captions] gives it */
export const CAPTION_NAMES = {
  'zh': { figure: '\u56fe', table: '\u8868' },
  'zh-Hant': { figure: '\u5716', table: '\u8868' },
  'ja': { figure: '\u56f3', table: '\u8868' },
  'ko': { figure: '\uadf8\ub9bc', table: '\ud45c' },
  'de': { figure: 'Abbildung', table: 'Tabelle' },
  'es': { figure: 'Figura', table: 'Cuadro' },
  'fr': { figure: 'Figure', table: 'Table' },
  'pt': { figure: 'Figura', table: 'Tabela' },
  'ru': { figure: '\u0420\u0438\u0441.', table: '\u0422\u0430\u0431\u043b\u0438\u0446\u0430' },
}

/** the names a final into `lang` gives a figure and a table: the first of the tags scripts.mjs babelTags tries that babel
 *  has a file for, as the final's \babelprovide takes it; null for a language no file names */
export function captionNames(lang) {
  const l = new Intl.Locale(lang)
  for (const tag of [lang, `${l.language}-${l.maximize().script}`, l.language]) if (Object.hasOwn(CAPTION_NAMES, tag)) return CAPTION_NAMES[tag]
  return null
}
