// font-coverage.mjs's types: the module is generated by scripts/font-roles.py from the face files of font-roles.mjs
import type { FaceId } from './font-roles.mjs'

/** each face's code points, as ranges: start, end (inclusive), sorted, disjoint; its cmap's, but controls and private use
 *  (whose glyphs mean what each font makes them mean): a text holding one is not drawable */
export declare const COVERAGE: Readonly<Record<FaceId, readonly number[]>>
/** each face's metrics in its own units: its em, hhea's ascent and descent (the descent below the baseline, positive),
 *  whether it has small capitals (GSUB smcp), and its file's SHA-256 */
export declare const METRICS: Readonly<Record<FaceId, { unitsPerEm: number; ascent: number; descent: number; smcp: boolean; sha256: string }>>
/** where the files come from: each source's release (source-han-serif: its tag; texlive: the image by digest) */
export declare const COVERAGE_SOURCE: { release: Readonly<Record<string, string>> }
