// lab/pdf/layer-lab/strings.mjs
// The layer lab's words, in its two interface languages: Chinese (the default, the maintainer's) and English. One table,
// both complete: lab.mjs checks at start that the two hold the same keys. A string is plain text, or a function of the
// values it names, so that each language orders its own sentence. Technical identifiers (commits, paths, fixture ids,
// the engine's own names for its fit actions) are values, never translated; the lab shows them under its technical
// details. The target languages are named in their own languages whatever the interface's (ENDONYMS).

/** the target languages by their own names, in either interface language */
export const ENDONYMS = { zh: '简体中文', 'zh-TW': '繁體中文', ja: '日本語', ko: '한국어', de: 'Deutsch', fr: 'Français', es: 'Español', ru: 'Русский' }
/** the interface languages, each by its own name */
export const UI_LANGS = { zh: '中文', en: 'English' }

const ms = n => (n == null || Number.isNaN(n) ? '-' : (+n).toFixed(1))

export const STRINGS = {
  zh: {
    htmlLang: 'zh-CN',
    title: '速览实验台',
    paper: '论文',
    target: '目标语言',
    pages: '翻页',
    prev: '上一页',
    next: '下一页',
    pageField: '页码',
    pageOf: (n, final) => `/ ${n}${final != null && final !== n ? ` · 定稿 ${final}` : ''}`,
    zoom: '缩放',
    zoomFit: '适合宽度',
    scroll: '滚动方式',
    scrollContinuous: '连续',
    scrollSingle: '单页',
    sync: '同步翻页',
    syncHint: '翻动一栏时，另一栏跟到同一位置',
    panel: '设置',
    settings: '设置面板',
    paneA: '左栏',
    paneB: '右栏',
    paneRegion: side => `${side}的页面`,
    views: { original: '原文', v0: '速览', layer: '早期引擎（已停用）', final: '定稿' },
    finalOlder: '译文早于当前一版',
    headOriginal: 'arXiv 的 PDF',
    headFinalOk: (strategy, typeset) => `${strategy ?? '未知方式'}${typeset ? ' · 排版规则' : ''}`,
    headFinalFailed: '编译失败',
    headFinalNone: '尚未编译',
    headV0: s => [s.fill === 'B' ? 'B 按原文行距' : 'D 自适应填充', s.tex ? 'TeX 几何' : '原型几何', s.removal ? '去字' : '擦除补回', ...(s.faces === 'prototype' ? ['原型字体'] : [])].join(' · '),
    headNotLoaded: '引擎未加载',
    headNotReady: '引擎未就绪',
    headNotDrawn: '未能绘制',

    // the side panel: the quick view's settings
    fill: '填充方式',
    fillD: 'D 自适应填充',
    fillB: 'B 按原文行距',
    fillHintD: '段落排不满时，先放宽行距，再加字距，最后放大字号。',
    fillHintB: '按原文的行距排，不做额外填充。',
    band: '行距浮动',
    bandHint: '最多高出本页行距中位数',
    track: '字距上限',
    size: '字号上限',
    sizeHint: '相对原文字号',
    unitEm: 'em',
    resetDefaults: '恢复默认',
    tex: 'TeX 精确几何',
    texDesc: '排版文件完整定位到的段落按它的行框排，其余按原型自己的几何。',
    removal: '去字附加层',
    removalDesc: '绘制在去掉原文文字的页面上；关闭则逐段擦除再补回。',
    faces: '原型字体',
    facesDesc: '使用原型自带的字体；关闭则按字体角色表选字体。',
    needsLayout: '这篇论文没有排版文件，此项不可用。',
    thisPage: p => `第 ${p} 页`,
    notDrawnYet: '本页尚未绘制。',
    rowUnits: '段落',
    rowRemoval: '去字',
    rowTime: '用时',
    v0Units: (n, tex, own, left) => `${n} 段：TeX 几何 ${tex} 段，原型几何 ${own} 段${left ? `；另有 ${left} 段保留原文` : ''}`,
    removalOff: '已关闭，逐段擦除再补回',
    removalDone: (tex, old) => `已去字：${tex} 段绘制在去字页上${old ? `，${old} 段擦除补回` : ''}`,
    removalNone: '本页没有去字，逐段擦除再补回',
    v0Time: (total, engine, pane) => `${ms(total)} ms（引擎 ${ms(engine)}，本栏 ${ms(pane)}）`,
    v0TimeAhead: '翻到其他页时已绘制',
    tech: '技术详情',
    techFit: '调整',
    techSteps: '引擎分步',
    techSteps1: t => `渲染 ${ms(t.render)}，取字 ${ms(t.text)}，排版 ${ms(t.lay)}，绘制指令 ${ms(t.ops)}，SVG ${ms(t.svg)}`,
    techWaited: '等待',
    techWaited1: (w, first) => `${ms(w)} ms（含为整页均衡预先绘制的页${first ? '；第 1 页还要加载字体' : ''}）`,
    techPaneRender: '原页渲染',
    techPaneRender1: (r, k) => `${ms(r)} ms，每单位 ${(+k).toFixed(2)} 像素`,
    techEngine: '引擎',
    techEngine1: (root, commit, remover) => `${root}，${commit}（去字程序 ${remover}）`,
    techInputs: '输入',
    techInputs1: i => `样本 ${i.fixtures ?? '-'}；译文 ${i.records ?? '与样本同处'}；几何 ${i.geometry ?? '-'}`,
    v0NotLoaded: why => `速览引擎未加载：${why}`,

    // the early engine (Task 11's entry, retired): what its pane says where an old link opens it
    layerNotReady: why => `引擎未就绪：${why}`,
    layerRefused: why => `排版文件生成器拒绝了这篇论文（${why}），阅读器在这里会按 Plan 5 的方式运行。`,
    layerNoLayout: err => `没有排版文件${err ? `（${err}）` : ''}。`,
    layerNoUnits: '没有 units.json，没有可排的内容。',
    layerCouldNotStart: err => `早期引擎无法启动：${err}`,
    rowWhy: '保留原因',
    rowFit: '调整',
    inspect: '指针下的段落',
    inspectHint: '点击页面上的段落，在此查看它的详情。',
    rowTranslation: '译文',
    translation1: (state, by, pieces, sentences) => `${state}，来自 ${by}；${pieces} 片，${sentences} 个句首`,
    translationNone: '无（保留或未译）',
    rowV0: '速览',
    v0Drawn: (by, s) => `已排入，按${by === 'tex' ? ' TeX 几何' : '原型几何'}：${s}`,
    v0Left: why => `保留原文：${why}`,
    v0NotLaid: '尚未排版（或未译）',
    rowLayout: '排版文件',
    layout1: (lines, frames, ph, lost, empty) => `${lines} 行，${frames} 个框，${ph} 个占位符（丢失 ${lost}，空 ${empty}）`,

    // the side panel: the paper
    rowTr: '译文',
    tr1: t => `${t.source}${t.pipeline != null ? ` · PIPELINE ${t.pipeline}` : ''}：${t.units} 段，其中 ${t.sentences} 段带句子边界`,
    trNone: '无',
    rowLayoutFile: '排版文件',
    layoutFile1: (units, pages) => `已定位 ${units} 段，共 ${pages} 页`,
    layoutRefused: why => `已拒绝（${why}）`,
    layoutNone: '无',
    rowFinal: '定稿',
    final1: f => `${f.strategy ?? '-'}${f.typeset ? ' · 排版规则' : ''} · ${f.settled ? '已收敛' : '未收敛'}${f.inSource ? ` · 源文件内 ${f.inSource} 处` : ''}`,
    finalFailed: f => `编译失败（${f.strategy ?? '-'}）`,
    finalNone: '尚未编译',
    rowFixture: '样本',
    rowStaging: '译文生成于',
    rowLayoutVersion: '排版文件版本',
    rowFinalMade: '定稿编译',
    finalMade1: f => `引擎 ${f.engine?.slice(0, 8) ?? '-'}，镜像 ${f.image?.slice(7, 19) ?? '-'}，${Math.round((f.ms ?? 0) / 1000)} 秒${f.from === 'finals' ? '；由实验台自带的样本编译，译文是更早的一版' : ''}`,
    rowFacesNote: '字体',
    facesNote: '定稿用当前 TeX 流程的字体；速览用字体角色表（可改用原型字体）。',
    rowLab: '实验台',
    lab1: (commit, subject) => `${commit ?? '-'} ${subject ?? ''}`,

    // the panes
    nothingToShow: '没有可显示的内容。',
    finalCannot: (strategy, error) => `当前的 TeX 流程排不出这份译文（最后的方式 ${strategy ?? '-'}：${error ?? '没有 PDF'}）。`,
    finalNotYet: '这份样本没有定稿。',
    bannerNoV0: why => `速览引擎未加载：${why}。`,
    bannerNoRecord: '这份样本没有 record.json，速览没有可排的内容。',
    bannerNoGeometry: '这篇论文没有几何数据（LAYER_GEOMETRY），速览没有可排的位置。',
    bannerV0Failed: (p, e) => `速览在第 ${p} 页出错：${e}`,
    bannerV0NoPage: p => `速览没有第 ${p} 页。`,
    bannerV0CouldNotDraw: (p, e) => `速览无法绘制第 ${p} 页：${e}`,
    bannerLayerFailed: (p, e) => `早期引擎在第 ${p} 页出错：${e}`,
    noFixtures: '还没有样本：先运行 lab/pdf/spikes/layer-fixtures.mjs。',

    // the notes and the footer
    notes: '笔记',
    notesPlaceholder: '记下在这篇论文、这种语言里看到的问题',
    exportNotes: '导出全部笔记',
    saved: time => `已保存 ${time}`,
    uiLang: '界面语言',
    keys: '快捷键',
    keysTurn: '翻页',

    // the status line
    opening: name => `正在打开 ${name}`,
    drawing: p => `正在绘制第 ${p} 页`,
    laying: p => `正在排版第 ${p} 页`,
    addon: '正在读取去字附加层',
  },

  en: {
    htmlLang: 'en',
    title: 'Layer lab',
    paper: 'Paper',
    target: 'Target language',
    pages: 'Pages',
    prev: 'Previous page',
    next: 'Next page',
    pageField: 'Page',
    pageOf: (n, final) => `/ ${n}${final != null && final !== n ? ` · final ${final}` : ''}`,
    zoom: 'Zoom',
    zoomFit: 'Fit width',
    scroll: 'Scrolling',
    scrollContinuous: 'Continuous',
    scrollSingle: 'One page',
    sync: 'Sync pages',
    syncHint: 'Scrolling one pane brings the other to the same place',
    panel: 'Settings',
    settings: 'Settings panel',
    paneA: 'Left pane',
    paneB: 'Right pane',
    paneRegion: side => `${side} pages`,
    views: { original: 'Original', v0: 'Quick view', layer: 'Early engine (retired)', final: 'Final' },
    finalOlder: 'from an earlier translation',
    headOriginal: "arXiv's PDF",
    headFinalOk: (strategy, typeset) => `${strategy ?? 'unknown'}${typeset ? ' · typesetting rule' : ''}`,
    headFinalFailed: 'Failed to compile',
    headFinalNone: 'Not compiled',
    headV0: s => [s.fill === 'B' ? 'B · original pitch' : 'D · adaptive fill', s.tex ? 'TeX geometry' : "prototype's geometry", s.removal ? 'text removed' : 'erased and put back', ...(s.faces === 'prototype' ? ["prototype's faces"] : [])].join(' · '),
    headNotLoaded: 'Engine not loaded',
    headNotReady: 'Engine not ready',
    headNotDrawn: 'Not drawn',

    fill: 'Fill',
    fillD: 'D · Adaptive',
    fillB: 'B · Original pitch',
    fillHintD: 'A unit that falls short of its space takes more leading, then tracking, then size.',
    fillHintB: "Set on the original's line pitch, with no extra fill.",
    band: 'Leading range',
    bandHint: "At most this far above the page's median",
    track: 'Tracking limit',
    size: 'Size limit',
    sizeHint: "Times the original's size",
    unitEm: 'em',
    resetDefaults: 'Restore defaults',
    tex: 'TeX geometry',
    texDesc: "Units the layout file locates whole take its line boxes; the rest take the prototype's own.",
    removal: 'Text-removed add-on',
    removalDesc: 'Draws over pages with the original text removed; off, each unit is erased and put back.',
    faces: "Prototype's faces",
    facesDesc: "Uses the prototype's own faces; off, the role table chooses them.",
    needsLayout: 'Unavailable: this paper has no layout file.',
    thisPage: p => `Page ${p}`,
    notDrawnYet: 'This page is not drawn yet.',
    rowUnits: 'Units',
    rowRemoval: 'Removal',
    rowTime: 'Time',
    v0Units: (n, tex, own, left) => `${n}: ${tex} by TeX geometry, ${own} by the prototype's${left ? `; ${left} more left as the original` : ''}`,
    removalOff: 'Off: each unit erased and put back',
    removalDone: (tex, old) => `Removed: ${tex} drawn over the removed page${old ? `, ${old} erased and put back` : ''}`,
    removalNone: 'Not removed on this page: each unit erased and put back',
    v0Time: (total, engine, pane) => `${ms(total)} ms (engine ${ms(engine)}, this pane ${ms(pane)})`,
    v0TimeAhead: 'Drawn on the way to another page',
    tech: 'Technical details',
    techFit: 'Fit',
    techSteps: 'Engine steps',
    techSteps1: t => `render ${ms(t.render)}, text ${ms(t.text)}, lay ${ms(t.lay)}, ops ${ms(t.ops)}, SVG ${ms(t.svg)}`,
    techWaited: 'Waited',
    techWaited1: (w, first) => `${ms(w)} ms (pages drawn ahead for the page pass included${first ? '; the first page loads the faces' : ''})`,
    techPaneRender: 'Page render',
    techPaneRender1: (r, k) => `${ms(r)} ms, ${(+k).toFixed(2)} px a unit`,
    techEngine: 'Engine',
    techEngine1: (root, commit, remover) => `${root} at ${commit} (remover ${remover})`,
    techInputs: 'Inputs',
    techInputs1: i => `fixtures ${i.fixtures ?? '-'}; translation ${i.records ?? 'beside them'}; geometry ${i.geometry ?? '-'}`,
    v0NotLoaded: why => `The quick view's engine is not loaded: ${why}`,

    layerNotReady: why => `Engine not ready: ${why}`,
    layerRefused: why => `The layout maker refused this paper (${why}): the reader runs as Plan 5's here.`,
    layerNoLayout: err => `No layout file${err ? ` (${err})` : ''}.`,
    layerNoUnits: 'No units.json: nothing to lay.',
    layerCouldNotStart: err => `The early engine could not start: ${err}`,
    rowWhy: 'Left, why',
    rowFit: 'Fit',
    inspect: 'Unit under the pointer',
    inspectHint: 'Click a unit on a page to see its details here.',
    rowTranslation: 'Translation',
    translation1: (state, by, pieces, sentences) => `${state} by ${by}; ${pieces} pieces, ${sentences} sentence starts`,
    translationNone: 'None (kept or untranslated)',
    rowV0: 'Quick view',
    v0Drawn: (by, s) => `Drawn by ${by === 'tex' ? 'TeX geometry' : "the prototype's geometry"}: ${s}`,
    v0Left: why => `Left as the original: ${why}`,
    v0NotLaid: 'Not laid yet (or not translated)',
    rowLayout: 'Layout',
    layout1: (lines, frames, ph, lost, empty) => `${lines} lines, ${frames} frames, ${ph} placeholders (${lost} lost, ${empty} empty)`,

    rowTr: 'Translation',
    tr1: t => `${t.source}${t.pipeline != null ? ` · PIPELINE ${t.pipeline}` : ''}: ${t.units} units, ${t.sentences} with sentence bounds`,
    trNone: 'None',
    rowLayoutFile: 'Layout file',
    layoutFile1: (units, pages) => `${units} units located, ${pages} pages`,
    layoutRefused: why => `Refused (${why})`,
    layoutNone: 'None',
    rowFinal: 'Final',
    final1: f => `${f.strategy ?? '-'}${f.typeset ? ' · typesetting rule' : ''} · ${f.settled ? 'settled' : 'not settled'}${f.inSource ? ` · ${f.inSource} in source` : ''}`,
    finalFailed: f => `Failed to compile (${f.strategy ?? '-'})`,
    finalNone: 'Not compiled',
    rowFixture: 'Fixture',
    rowStaging: 'Translated',
    rowLayoutVersion: 'Layout version',
    rowFinalMade: 'Final made',
    finalMade1: f => `engine ${f.engine?.slice(0, 8) ?? '-'}, image ${f.image?.slice(7, 19) ?? '-'}, ${Math.round((f.ms ?? 0) / 1000)} s${f.from === 'finals' ? "; compiled from the lab's own fixture, its translation an earlier cut's" : ''}`,
    rowFacesNote: 'Faces',
    facesNote: "The final uses today's TeX faces; the quick view the role table's (or the prototype's own, where asked).",
    rowLab: 'Lab',
    lab1: (commit, subject) => `${commit ?? '-'} ${subject ?? ''}`,

    nothingToShow: 'Nothing to show.',
    finalCannot: (strategy, error) => `Today's TeX path could not set this translation (last strategy ${strategy ?? '-'}: ${error ?? 'no PDF'}).`,
    finalNotYet: 'No final for this fixture.',
    bannerNoV0: why => `No quick view: ${why}.`,
    bannerNoRecord: 'No record.json for this fixture: the quick view has nothing to lay.',
    bannerNoGeometry: 'No geometry for this paper (LAYER_GEOMETRY): the quick view has no anchors to lay on.',
    bannerV0Failed: (p, e) => `The quick view failed on page ${p}: ${e}`,
    bannerV0NoPage: p => `The quick view shows no page ${p}.`,
    bannerV0CouldNotDraw: (p, e) => `The quick view could not draw page ${p}: ${e}`,
    bannerLayerFailed: (p, e) => `The early engine failed on page ${p}: ${e}`,
    noFixtures: 'No fixtures yet: run lab/pdf/spikes/layer-fixtures.mjs first.',

    notes: 'Notes',
    notesPlaceholder: 'What you see in this paper and language',
    exportNotes: 'Export all notes',
    saved: time => `Saved ${time}`,
    uiLang: 'Interface language',
    keys: 'Shortcuts',
    keysTurn: 'turn pages',

    opening: name => `Opening ${name}`,
    drawing: p => `Drawing page ${p}`,
    laying: p => `Laying page ${p}`,
    addon: 'Reading the text-removed add-on',
  },
}

/** the keys one language has and the other has not (nested tables included): empty when both are complete */
export function missingKeys(a = STRINGS.zh, b = STRINGS.en, at = '') {
  const out = []
  for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
    if (!(k in a) || !(k in b)) { out.push(`${at}${k}`); continue }
    const x = a[k], y = b[k]
    if (typeof x !== typeof y || Array.isArray(x) !== Array.isArray(y)) out.push(`${at}${k}`)
    else if (x && typeof x === 'object' && !Array.isArray(x)) out.push(...missingKeys(x, y, `${at}${k}.`))
  }
  return out
}
