// 移植自 @read-frog/definitions@0.4.4（reference/read-frog 的依赖包，GPL-3.0）的语言表，2026-09-05 移植、有修改：
// 只搬 LANG_CODE_ISO6393_OPTIONS 与四张名称 / 映射表，其余（SRS、电子书 schema）不搬；辅助函数是本项目的。
// 语言码用 ISO 639-3（与 Read Frog 一致），配置 v4 起 targetLanguage 存这个码；
// LLM prompt 里填英文名，Google 网页翻译按 BCP-47 收，各自经这里的函数转换。
import { z } from 'zod'

/** 179 个 ISO 639-3 码，顺序照 Read Frog（常用语言在前） */
export const LANG_CODES = [
  "eng",
  "cmn",
  "cmn-Hant",
  "yue",
  "spa",
  "rus",
  "arb",
  "ben",
  "hin",
  "por",
  "ind",
  "jpn",
  "fra",
  "deu",
  "jav",
  "kor",
  "tel",
  "vie",
  "mar",
  "ita",
  "tam",
  "tur",
  "urd",
  "guj",
  "pol",
  "ukr",
  "kan",
  "mai",
  "mal",
  "pes",
  "mya",
  "swh",
  "sun",
  "ron",
  "pan",
  "bho",
  "amh",
  "hau",
  "fuv",
  "bos",
  "hrv",
  "nld",
  "srp",
  "tha",
  "ckb",
  "yor",
  "uzn",
  "zlm",
  "ibo",
  "npi",
  "ceb",
  "skr",
  "tgl",
  "hun",
  "azj",
  "sin",
  "koi",
  "ell",
  "ces",
  "mag",
  "run",
  "bel",
  "plt",
  "qug",
  "mad",
  "nya",
  "zyb",
  "pbu",
  "kin",
  "zul",
  "bul",
  "swe",
  "lin",
  "som",
  "hms",
  "hnj",
  "ilo",
  "kaz",
  "heb",
  "nob",
  "nno",
  "afr",
  "sqi",
  "asm",
  "eus",
  "bre",
  "cat",
  "cos",
  "cym",
  "dan",
  "div",
  "epo",
  "ekk",
  "fao",
  "fij",
  "fin",
  "fry",
  "gla",
  "gle",
  "glg",
  "grn",
  "hat",
  "haw",
  "hye",
  "ido",
  "ina",
  "isl",
  "kat",
  "khm",
  "kir",
  "lao",
  "lat",
  "lvs",
  "lit",
  "ltz",
  "mkd",
  "mlt",
  "mon",
  "mri",
  "nso",
  "oci",
  "ori",
  "orm",
  "prs",
  "san",
  "slk",
  "slv",
  "smo",
  "sna",
  "snd",
  "sot",
  "tah",
  "tat",
  "tgk",
  "tir",
  "ton",
  "tsn",
  "tuk",
  "uig",
  "vol",
  "wol",
  "xho",
  "ydd",
  "aka",
  "bam",
  "bis",
  "bod",
  "che",
  "chv",
  "dzo",
  "ewe",
  "kab",
  "lug",
  "oss",
  "ssw",
  "ven",
  "war",
  "nde",
  "nbl",
  "pam",
  "hil",
  "bcl",
  "min",
  "ace",
  "bug",
  "ban",
  "bjn",
  "mak",
  "sas",
  "tet",
  "cha",
  "niu",
  "tvl",
  "gil",
  "mah",
  "pau",
  "wls",
  "rar",
  "hif",
] as const

export type LangCode = (typeof LANG_CODES)[number]

export const langCodeSchema = z.enum(LANG_CODES)

/** 英文语言名：填进 LLM prompt 的 {{targetLanguage}}（Read Frog translate-text.ts 的做法） */
export const LANG_CODE_TO_EN_NAME = {
  "eng": "English",
  "cmn": "Simplified Mandarin Chinese",
  "cmn-Hant": "Traditional Mandarin Chinese",
  "yue": "Cantonese",
  "spa": "Spanish",
  "rus": "Russian",
  "arb": "Standard Arabic",
  "ben": "Bengali",
  "hin": "Hindi",
  "por": "Portuguese",
  "ind": "Indonesian",
  "jpn": "Japanese",
  "fra": "French",
  "deu": "German",
  "jav": "Javanese (Javanese)",
  "kor": "Korean",
  "tel": "Telugu",
  "vie": "Vietnamese",
  "mar": "Marathi",
  "ita": "Italian",
  "tam": "Tamil",
  "tur": "Turkish",
  "urd": "Urdu",
  "guj": "Gujarati",
  "pol": "Polish",
  "ukr": "Ukrainian",
  "kan": "Kannada",
  "mai": "Maithili",
  "mal": "Malayalam",
  "pes": "Iranian Persian",
  "mya": "Burmese",
  "swh": "Swahili (individual language)",
  "sun": "Sundanese",
  "ron": "Romanian",
  "pan": "Panjabi",
  "bho": "Bhojpuri",
  "amh": "Amharic",
  "hau": "Hausa",
  "fuv": "Nigerian Fulfulde",
  "bos": "Bosnian (Cyrillic)",
  "hrv": "Croatian",
  "nld": "Dutch",
  "srp": "Serbian (Cyrillic)",
  "tha": "Thai",
  "ckb": "Central Kurdish",
  "yor": "Yoruba",
  "uzn": "Northern Uzbek (Cyrillic)",
  "zlm": "Malay (individual language) (Arabic)",
  "ibo": "Igbo",
  "npi": "Nepali (individual language)",
  "ceb": "Cebuano",
  "skr": "Saraiki",
  "tgl": "Tagalog",
  "hun": "Hungarian",
  "azj": "North Azerbaijani (Cyrillic)",
  "sin": "Sinhala",
  "koi": "Komi-Permyak",
  "ell": "Modern Greek (1453-)",
  "ces": "Czech",
  "mag": "Magahi",
  "run": "Rundi",
  "bel": "Belarusian",
  "plt": "Plateau Malagasy",
  "qug": "Chimborazo Highland Quichua",
  "mad": "Madurese",
  "nya": "Nyanja",
  "zyb": "Yongbei Zhuang",
  "pbu": "Northern Pashto",
  "kin": "Kinyarwanda",
  "zul": "Zulu",
  "bul": "Bulgarian",
  "swe": "Swedish",
  "lin": "Lingala",
  "som": "Somali",
  "hms": "Southern Qiandong Miao",
  "hnj": "Hmong Njua",
  "ilo": "Iloko",
  "kaz": "Kazakh",
  "heb": "Hebrew",
  "nob": "Norwegian Bokmål",
  "nno": "Norwegian Nynorsk",
  "afr": "Afrikaans",
  "sqi": "Albanian",
  "asm": "Assamese",
  "eus": "Basque",
  "bre": "Breton",
  "cat": "Catalan",
  "cos": "Corsican",
  "cym": "Welsh",
  "dan": "Danish",
  "div": "Divehi",
  "epo": "Esperanto",
  "ekk": "Estonian",
  "fao": "Faroese",
  "fij": "Fijian",
  "fin": "Finnish",
  "fry": "Western Frisian",
  "gla": "Scottish Gaelic",
  "gle": "Irish",
  "glg": "Galician",
  "grn": "Guarani",
  "hat": "Haitian Creole",
  "haw": "Hawaiian",
  "hye": "Armenian",
  "ido": "Ido",
  "ina": "Interlingua",
  "isl": "Icelandic",
  "kat": "Georgian",
  "khm": "Khmer",
  "kir": "Kyrgyz",
  "lao": "Lao",
  "lat": "Latin",
  "lvs": "Latvian",
  "lit": "Lithuanian",
  "ltz": "Luxembourgish",
  "mkd": "Macedonian",
  "mlt": "Maltese",
  "mon": "Mongolian",
  "mri": "Maori",
  "nso": "Northern Sotho",
  "oci": "Occitan",
  "ori": "Odia",
  "orm": "Oromo",
  "prs": "Dari",
  "san": "Sanskrit",
  "slk": "Slovak",
  "slv": "Slovenian",
  "smo": "Samoan",
  "sna": "Shona",
  "snd": "Sindhi",
  "sot": "Southern Sotho",
  "tah": "Tahitian",
  "tat": "Tatar",
  "tgk": "Tajik",
  "tir": "Tigrinya",
  "ton": "Tongan",
  "tsn": "Tswana",
  "tuk": "Turkmen",
  "uig": "Uyghur",
  "vol": "Volapük",
  "wol": "Wolof",
  "xho": "Xhosa",
  "ydd": "Eastern Yiddish",
  "aka": "Akan",
  "bam": "Bambara",
  "bis": "Bislama",
  "bod": "Tibetan",
  "che": "Chechen",
  "chv": "Chuvash",
  "dzo": "Dzongkha",
  "ewe": "Ewe",
  "kab": "Kabyle",
  "lug": "Ganda",
  "oss": "Ossetian",
  "ssw": "Swati",
  "ven": "Venda",
  "war": "Waray",
  "nde": "North Ndebele",
  "nbl": "South Ndebele",
  "pam": "Pampanga",
  "hil": "Hiligaynon",
  "bcl": "Central Bikol",
  "min": "Minangkabau",
  "ace": "Acehnese",
  "bug": "Buginese",
  "ban": "Balinese",
  "bjn": "Banjar",
  "mak": "Makasar",
  "sas": "Sasak",
  "tet": "Tetum",
  "cha": "Chamorro",
  "niu": "Niuean",
  "tvl": "Tuvaluan",
  "gil": "Gilbertese",
  "mah": "Marshallese",
  "pau": "Palauan",
  "wls": "Wallisian",
  "rar": "Rarotongan",
  "hif": "Fiji Hindi",
} as const satisfies Record<LangCode, string>

/** 中文语言名：设置页显示用 */
export const LANG_CODE_TO_ZH_NAME = {
  "eng": "英语",
  "cmn": "简体中文",
  "cmn-Hant": "繁体中文",
  "yue": "粤语",
  "spa": "西班牙语",
  "rus": "俄语",
  "arb": "阿拉伯语",
  "ben": "孟加拉语",
  "hin": "印地语",
  "por": "葡萄牙语",
  "ind": "印尼语",
  "jpn": "日语",
  "fra": "法语",
  "deu": "德语",
  "jav": "爪哇语",
  "kor": "韩语",
  "tel": "泰卢固语",
  "vie": "越南语",
  "mar": "马拉地语",
  "ita": "意大利语",
  "tam": "泰米尔语",
  "tur": "土耳其语",
  "urd": "乌尔都语",
  "guj": "古吉拉特语",
  "pol": "波兰语",
  "ukr": "乌克兰语",
  "kan": "坎纳达语",
  "mai": "迈蒂利语",
  "mal": "马拉雅拉姆语",
  "pes": "波斯语",
  "mya": "缅甸语",
  "swh": "斯瓦希里语",
  "sun": "巽他语",
  "ron": "罗马尼亚语",
  "pan": "旁遮普语",
  "bho": "博杰普尔语",
  "amh": "阿姆哈拉语",
  "hau": "豪萨语",
  "fuv": "富拉语",
  "bos": "波斯尼亚语",
  "hrv": "克罗地亚语",
  "nld": "荷兰语",
  "srp": "塞尔维亚语",
  "tha": "泰语",
  "ckb": "库尔德语",
  "yor": "约鲁巴语",
  "uzn": "乌兹别克语",
  "zlm": "马来语",
  "ibo": "伊博语",
  "npi": "尼泊尔语",
  "ceb": "宿务语",
  "skr": "旁遮普语",
  "tgl": "塔加路语",
  "hun": "匈牙利语",
  "azj": "北阿塞拜疆语",
  "sin": "僧伽罗语",
  "koi": "科米-彼尔姆语",
  "ell": "现代希腊语",
  "ces": "捷克语",
  "mag": "马加哈语",
  "run": "鲁恩达语",
  "bel": "白俄罗斯语",
  "plt": "高原马达加斯加语",
  "qug": "奇布查语",
  "mad": "马都拉语",
  "nya": "尼扬加语",
  "zyb": "壮语",
  "pbu": "北部普什图语",
  "kin": "基尼亚卢旺达语",
  "zul": "祖鲁语",
  "bul": "保加利亚语",
  "swe": "瑞典语",
  "lin": "林加拉语",
  "som": "索马里语",
  "hms": "南部乾东苗语",
  "hnj": "苗族北部语",
  "ilo": "伊洛卡诺语",
  "kaz": "哈萨克语",
  "heb": "希伯来语",
  "nob": "书面挪威语",
  "nno": "新挪威语",
  "afr": "南非荷兰语",
  "sqi": "阿尔巴尼亚语",
  "asm": "阿萨姆语",
  "eus": "巴斯克语",
  "bre": "布列塔尼语",
  "cat": "加泰罗尼亚语",
  "cos": "科西嘉语",
  "cym": "威尔士语",
  "dan": "丹麦语",
  "div": "迪维希语",
  "epo": "世界语",
  "ekk": "爱沙尼亚语",
  "fao": "法罗语",
  "fij": "斐济语",
  "fin": "芬兰语",
  "fry": "西弗里西亚语",
  "gla": "苏格兰盖尔语",
  "gle": "爱尔兰语",
  "glg": "加利西亚语",
  "grn": "瓜拉尼语",
  "hat": "海地克里奥尔语",
  "haw": "夏威夷语",
  "hye": "亚美尼亚语",
  "ido": "伊多语",
  "ina": "国际辅助语",
  "isl": "冰岛语",
  "kat": "格鲁吉亚语",
  "khm": "高棉语",
  "kir": "吉尔吉斯语",
  "lao": "老挝语",
  "lat": "拉丁语",
  "lvs": "拉脱维亚语",
  "lit": "立陶宛语",
  "ltz": "卢森堡语",
  "mkd": "马其顿语",
  "mlt": "马耳他语",
  "mon": "蒙古语",
  "mri": "毛利语",
  "nso": "北索托语",
  "oci": "奥克语",
  "ori": "奥里亚语",
  "orm": "奥罗莫语",
  "prs": "达里语",
  "san": "梵语",
  "slk": "斯洛伐克语",
  "slv": "斯洛文尼亚语",
  "smo": "萨摩亚语",
  "sna": "绍纳语",
  "snd": "信德语",
  "sot": "南索托语",
  "tah": "塔希提语",
  "tat": "鞑靼语",
  "tgk": "塔吉克语",
  "tir": "提格雷尼亚语",
  "ton": "汤加语",
  "tsn": "茨瓦纳语",
  "tuk": "土库曼语",
  "uig": "维吾尔语",
  "vol": "沃拉普克语",
  "wol": "沃洛夫语",
  "xho": "科萨语",
  "ydd": "东意第绪语",
  "aka": "阿坎语",
  "bam": "班巴拉语",
  "bis": "比斯拉马语",
  "bod": "藏语",
  "che": "车臣语",
  "chv": "楚瓦什语",
  "dzo": "宗喀语",
  "ewe": "埃维语",
  "kab": "卡拜尔语",
  "lug": "卢干达语",
  "oss": "奥塞梯语",
  "ssw": "斯瓦蒂语",
  "ven": "文达语",
  "war": "瓦瑞语",
  "nde": "北恩德贝勒语",
  "nbl": "南恩德贝勒语",
  "pam": "邦板牙语",
  "hil": "希利盖农语",
  "bcl": "中比科尔语",
  "min": "米南佳保语",
  "ace": "亚齐语",
  "bug": "布吉语",
  "ban": "巴厘语",
  "bjn": "班贾尔语",
  "mak": "望加锡语",
  "sas": "萨萨克语",
  "tet": "德顿语",
  "cha": "查莫罗语",
  "niu": "纽埃语",
  "tvl": "图瓦卢语",
  "gil": "吉尔伯特语",
  "mah": "马绍尔语",
  "pau": "帕劳语",
  "wls": "瓦利斯语",
  "rar": "拉罗汤加语",
  "hif": "斐济印地语",
} as const satisfies Record<LangCode, string>

/** 该语言自己的写法 */
export const LANG_CODE_TO_LOCALE_NAME = {
  "eng": "English",
  "cmn": "简体中文",
  "cmn-Hant": "繁體中文",
  "yue": "粵語",
  "spa": "Español",
  "rus": "Русский",
  "arb": "العربية",
  "ben": "বাংলা",
  "hin": "हिन्दी",
  "por": "Português",
  "ind": "Bahasa Indonesia",
  "jpn": "日本語",
  "fra": "Français",
  "deu": "Deutsch",
  "jav": "Basa Jawa",
  "kor": "한국어",
  "tel": "తెలుగు",
  "vie": "Tiếng Việt",
  "mar": "मराठी",
  "ita": "Italiano",
  "tam": "தமிழ்",
  "tur": "Türkçe",
  "urd": "اردو",
  "guj": "ગુજરાતી",
  "pol": "Polski",
  "ukr": "Українська",
  "kan": "ಕನ್ನಡ",
  "mai": "मैथिली",
  "mal": "മലയാളം",
  "pes": "فارسی",
  "mya": "မြန်မာစာ",
  "swh": "Kiswahili",
  "sun": "Basa Sunda",
  "ron": "Română",
  "pan": "ਪੰਜਾਬੀ",
  "bho": "भोजपुरी",
  "amh": "አማርኛ",
  "hau": "Hausa",
  "fuv": "Fulfulde",
  "bos": "Босански",
  "hrv": "Hrvatski",
  "nld": "Nederlands",
  "srp": "Српски",
  "tha": "ไทย",
  "ckb": "کوردیی ناوەندی",
  "yor": "Yorùbá",
  "uzn": "Ўзбекча",
  "zlm": "بهاس ملايو",
  "ibo": "Asụsụ Igbo",
  "npi": "नेपाली",
  "ceb": "Cebuano",
  "skr": "سرائیکی",
  "tgl": "Tagalog",
  "hun": "Magyar",
  "azj": "Азәрбајҹан дили",
  "sin": "සිංහල",
  "koi": "Перем Коми кыв",
  "ell": "Ελληνικά",
  "ces": "Čeština",
  "mag": "मगही",
  "run": "Ikirundi",
  "bel": "Беларуская",
  "plt": "Fiteny Malagasy",
  "qug": "Kichwa",
  "mad": "Madhurâ",
  "nya": "Chinyanja",
  "zyb": "Yongbei Bouxcuengh",
  "pbu": "پښتو",
  "kin": "Kinyarwanda",
  "zul": "isiZulu",
  "bul": "Български",
  "swe": "Svenska",
  "lin": "Lingála",
  "som": "Af Soomaali",
  "hms": "Hmongb Shuad",
  "hnj": "Hmong Njua",
  "ilo": "Ilokano",
  "kaz": "Қазақ тілі",
  "heb": "עברית",
  "nob": "Norsk bokmål",
  "nno": "Norsk nynorsk",
  "afr": "Afrikaans",
  "sqi": "Shqip",
  "asm": "অসমীয়া",
  "eus": "Euskara",
  "bre": "Brezhoneg",
  "cat": "Català",
  "cos": "Corsu",
  "cym": "Cymraeg",
  "dan": "Dansk",
  "div": "ދިވެހި",
  "epo": "Esperanto",
  "ekk": "Eesti",
  "fao": "Føroyskt",
  "fij": "Vosa Vakaviti",
  "fin": "Suomi",
  "fry": "Frysk",
  "gla": "Gàidhlig",
  "gle": "Gaeilge",
  "glg": "Galego",
  "grn": "Avañeʼẽ",
  "hat": "Kreyòl ayisyen",
  "haw": "ʻŌlelo Hawaiʻi",
  "hye": "Հایերен",
  "ido": "Ido",
  "ina": "Interlingua",
  "isl": "Íslenska",
  "kat": "ქართული",
  "khm": "ភាសាខ្មែរ",
  "kir": "Кыргызча",
  "lao": "ພາສາລາວ",
  "lat": "Latina",
  "lvs": "Latviešu",
  "lit": "Lietuvių",
  "ltz": "Lëtzebuergesch",
  "mkd": "Македонски",
  "mlt": "Malti",
  "mon": "Монгол",
  "mri": "Te Reo Māori",
  "nso": "Sesotho sa Leboa",
  "oci": "Occitan",
  "ori": "ଓଡ଼ିଆ",
  "orm": "Oromoo",
  "prs": "دری",
  "san": "संस्कृतम्",
  "slk": "Slovenčina",
  "slv": "Slovenščina",
  "smo": "Gagana Samoa",
  "sna": "chiShona",
  "snd": "سنڌي",
  "sot": "Sesotho",
  "tah": "Reo Tahiti",
  "tat": "Татарча",
  "tgk": "Тоҷикӣ",
  "tir": "ትግርኛ",
  "ton": "Lea fakatonga",
  "tsn": "Setswana",
  "tuk": "Türkmençe",
  "uig": "ئۇيغۇرچە",
  "vol": "Volapük",
  "wol": "Wolof",
  "xho": "isiXhosa",
  "ydd": "ייִדיש",
  "aka": "Akan",
  "bam": "Bamanankan",
  "bis": "Bislama",
  "bod": "བོད་སྐད",
  "che": "Нохчийн",
  "chv": "Чӑвашла",
  "dzo": "རྫོང་ཁ",
  "ewe": "Eʋegbe",
  "kab": "Taqbaylit",
  "lug": "Luganda",
  "oss": "Ирон",
  "ssw": "SiSwati",
  "ven": "Tshivenḓa",
  "war": "Winaray",
  "nde": "isiNdebele",
  "nbl": "isiNdebele seSewula",
  "pam": "Kapampangan",
  "hil": "Ilonggo",
  "bcl": "Bikol Sentral",
  "min": "Baso Minangkabau",
  "ace": "Bahsa Acèh",
  "bug": "Basa Ugi",
  "ban": "Basa Bali",
  "bjn": "Bahasa Banjar",
  "mak": "Basa Mangkasara",
  "sas": "Sasak",
  "tet": "Tetun",
  "cha": "Chamoru",
  "niu": "Vagahau Niuē",
  "tvl": "Te Gana Tuvalu",
  "gil": "Taetae ni Kiribati",
  "mah": "Kajin Majel",
  "pau": "A tekoi er a Belau",
  "wls": "Fakaʻuvea",
  "rar": "Māori Kūki ʻĀirani",
  "hif": "फ़िजी हिंदी",
} as const satisfies Record<LangCode, string>

/** ISO 639-3 → BCP-47（Google 等按 BCP-47 收目标语言）；38 个码没有对应的两字母码 */
export const ISO6393_TO_6391 = {
  "eng": "en",
  "cmn": "zh",
  "cmn-Hant": "zh-TW",
  "yue": "zh",
  "spa": "es",
  "rus": "ru",
  "arb": "ar",
  "ben": "bn",
  "hin": "hi",
  "por": "pt",
  "ind": "id",
  "jpn": "ja",
  "fra": "fr",
  "deu": "de",
  "jav": "jv",
  "kor": "ko",
  "tel": "te",
  "vie": "vi",
  "mar": "mr",
  "ita": "it",
  "tam": "ta",
  "tur": "tr",
  "urd": "ur",
  "guj": "gu",
  "pol": "pl",
  "ukr": "uk",
  "kan": "kn",
  "mal": "ml",
  "pes": "fa",
  "mya": "my",
  "swh": "sw",
  "sun": "su",
  "ron": "ro",
  "pan": "pa",
  "amh": "am",
  "hau": "ha",
  "fuv": "ff",
  "bos": "bs",
  "hrv": "hr",
  "nld": "nl",
  "srp": "sr",
  "tha": "th",
  "ckb": "ku",
  "yor": "yo",
  "uzn": "uz",
  "zlm": "ms",
  "ibo": "ig",
  "npi": "ne",
  "tgl": "tl",
  "hun": "hu",
  "azj": "az",
  "sin": "si",
  "ell": "el",
  "ces": "cs",
  "bel": "be",
  "nya": "ny",
  "kin": "rw",
  "zul": "zu",
  "bul": "bg",
  "swe": "sv",
  "lin": "ln",
  "som": "so",
  "kaz": "kk",
  "heb": "he",
  "nob": "nb",
  "nno": "nn",
  "afr": "af",
  "sqi": "sq",
  "asm": "as",
  "eus": "eu",
  "bre": "br",
  "cat": "ca",
  "cos": "co",
  "cym": "cy",
  "dan": "da",
  "div": "dv",
  "epo": "eo",
  "ekk": "et",
  "fao": "fo",
  "fij": "fj",
  "fin": "fi",
  "fry": "fy",
  "gla": "gd",
  "gle": "ga",
  "glg": "gl",
  "grn": "gn",
  "hat": "ht",
  "hye": "hy",
  "ido": "io",
  "ina": "ia",
  "isl": "is",
  "kat": "ka",
  "khm": "km",
  "kir": "ky",
  "lao": "lo",
  "lat": "la",
  "lvs": "lv",
  "lit": "lt",
  "ltz": "lb",
  "mkd": "mk",
  "mlt": "mt",
  "mon": "mn",
  "mri": "mi",
  "oci": "oc",
  "ori": "or",
  "orm": "om",
  "san": "sa",
  "slk": "sk",
  "slv": "sl",
  "smo": "sm",
  "sna": "sn",
  "snd": "sd",
  "sot": "st",
  "tah": "ty",
  "tat": "tt",
  "tgk": "tg",
  "tir": "ti",
  "ton": "to",
  "tsn": "tn",
  "tuk": "tk",
  "uig": "ug",
  "vol": "vo",
  "wol": "wo",
  "xho": "xh",
  "ydd": "yi",
  "aka": "ak",
  "bam": "bm",
  "bis": "bi",
  "bod": "bo",
  "che": "ce",
  "chv": "cv",
  "dzo": "dz",
  "ewe": "ee",
  "lug": "lg",
  "oss": "os",
  "ssw": "ss",
  "ven": "ve",
  "nde": "nd",
  "nbl": "nr",
  "cha": "ch",
  "mah": "mh",
} as const satisfies Partial<Record<LangCode, string>>

export const DEFAULT_LANG_CODE: LangCode = 'cmn'

export function isLangCode(value: string): value is LangCode {
  return (LANG_CODES as readonly string[]).includes(value)
}

/** 填进 prompt 的语言名；不认识的码原样返回（自定义或旧配置） */
export function englishName(code: string): string {
  return isLangCode(code) ? LANG_CODE_TO_EN_NAME[code] : code
}

/** 设置页显示：中文名（本地写法），对应 Read Frog language-labels.ts 的 getLanguageLabel */
export function label(code: LangCode): string {
  const zh = LANG_CODE_TO_ZH_NAME[code]
  const local = LANG_CODE_TO_LOCALE_NAME[code]
  return zh === local ? zh : `${zh}（${local}）`
}

/** 给按 BCP-47 收目标语言的引擎（google-web）；没有两字母码的语言原样传 ISO 639-3 码 */
const BCP47: Partial<Record<LangCode, string>> = ISO6393_TO_6391

/**
 * 两字母码丢掉了语言身份或文字，而端点其实分得清的，改发别的标签（Codex 在 #39 三轮指出，逐条实测）：
 * - yue 与 cmn 都是 zh，发 zh 就成了普通话（实测 yue 返回"巴士站喺邊"，zh 返回"公交车站在哪里"）
 * - ckb（索拉尼）与 kmr（库尔曼吉）都是 ku，发 ku 就成了库尔曼吉（实测 ckb 返回阿拉伯字母 "وێستگەی پاس"，ku 返回拉丁字母 "Rawestgeha"）
 * - zlm 在表里就叫 "Malay (individual language) (Arabic)"，发 ms 得到拉丁字母的马来语（实测 ms-Arab 返回爪夷文 "دمان ڤرهنتين بس؟"）
 *
 * 表里另外三个带文字标注的条目**端点做不到**，只能维持现状（实测 bs / bs-Cyrl、uz / uz-Cyrl、az / az-Cyrl 返回完全相同的拉丁字母结果）：
 * bos "Bosnian (Cyrillic)"、uzn "Northern Uzbek (Cyrillic)"、azj "North Azerbaijani (Cyrillic)"。
 * srp "Serbian (Cyrillic)" 本来就对（sr 一律返回西里尔字母）。LLM 路径不受影响：它拿的是英文名，文字标注在名字里
 */
const BCP47_OVERRIDES: Partial<Record<LangCode, string>> = { yue: 'yue', ckb: 'ckb', zlm: 'ms-Arab' }

export function toBcp47(code: string): string {
  if (!isLangCode(code)) return code
  return BCP47_OVERRIDES[code] ?? BCP47[code] ?? code
}

/**
 * BCP-47 → ISO 639-3，配置 v3→v4 迁移用。BCP-47 不分大小写（Codex 在 #39 指出）。
 * 依次：精确反查（zh-TW → cmn-Hant）；子标签相交——表里同主语言的条目中，取地区 / 文字子标签有交集的
 * （zh-Hant-TW ∩ zh-TW → cmn-Hant）；中文的繁体文字标签或港澳台地区（zh-Hant、zh-HK、zh-MO）表里没有对应条目，
 * 归 cmn-Hant（Codex 在 #39 第二轮指出：只按主语言回退会把繁体悄悄换成简体）；再按主语言回退
 * （zh-CN → zh → cmn，表里 cmn 排在 yue 前面）；都没有回退简体中文
 */
export function fromBcp47(tag: string): LangCode {
  if (isLangCode(tag)) return tag
  const wanted = tag.toLowerCase()
  const [primary = '', ...subtags] = wanted.split('-')
  const entries = (Object.entries(ISO6393_TO_6391) as [LangCode, string][]).map(([code, bcp]) => [code, bcp.toLowerCase().split('-')] as const)
  const exact = entries.find(([, parts]) => parts.join('-') === wanted)
  if (exact) return exact[0]
  const sameLanguage = entries.filter(([, parts]) => parts[0] === primary)
  const overlapping = sameLanguage.find(([, parts]) => parts.slice(1).some(part => subtags.includes(part)))
  if (overlapping) return overlapping[0]
  if (primary === 'zh' && subtags.some(part => TRADITIONAL_CHINESE_SUBTAGS.has(part))) return 'cmn-Hant'
  return sameLanguage[0]?.[0] ?? DEFAULT_LANG_CODE
}

/** 繁体中文的文字 / 地区子标签（小写） */
const TRADITIONAL_CHINESE_SUBTAGS = new Set(['hant', 'tw', 'hk', 'mo'])
