// Language tables ported from @read-frog/definitions@0.4.4 (reference/read-frog dependency, GPL-3.0), 2026-09-05; modified:
// Only LANG_CODE_ISO6393_OPTIONS and four name/mapping tables were ported; SRS and ebook schemas were omitted. Helpers are project-owned.
// ISO 639-3 codes match Read Frog; targetLanguage stores these codes since config v4.
// Helpers convert them to English names for LLM prompts and BCP-47 for Google web translation.
import { z } from 'zod'

/** 179 ISO 639-3 codes in Read Frog order (common languages first). */
export const LANG_CODES = [
  "eng",
  "cmn",
  "cmn-Hant",
  "yue",
  "spa",
  "rus",
  "arb",
  "ben",
  "hin",
  "por",
  "ind",
  "jpn",
  "fra",
  "deu",
  "jav",
  "kor",
  "tel",
  "vie",
  "mar",
  "ita",
  "tam",
  "tur",
  "urd",
  "guj",
  "pol",
  "ukr",
  "kan",
  "mai",
  "mal",
  "pes",
  "mya",
  "swh",
  "sun",
  "ron",
  "pan",
  "bho",
  "amh",
  "hau",
  "fuv",
  "bos",
  "hrv",
  "nld",
  "srp",
  "tha",
  "ckb",
  "yor",
  "uzn",
  "zlm",
  "ibo",
  "npi",
  "ceb",
  "skr",
  "tgl",
  "hun",
  "azj",
  "sin",
  "koi",
  "ell",
  "ces",
  "mag",
  "run",
  "bel",
  "plt",
  "qug",
  "mad",
  "nya",
  "zyb",
  "pbu",
  "kin",
  "zul",
  "bul",
  "swe",
  "lin",
  "som",
  "hms",
  "hnj",
  "ilo",
  "kaz",
  "heb",
  "nob",
  "nno",
  "afr",
  "sqi",
  "asm",
  "eus",
  "bre",
  "cat",
  "cos",
  "cym",
  "dan",
  "div",
  "epo",
  "ekk",
  "fao",
  "fij",
  "fin",
  "fry",
  "gla",
  "gle",
  "glg",
  "grn",
  "hat",
  "haw",
  "hye",
  "ido",
  "ina",
  "isl",
  "kat",
  "khm",
  "kir",
  "lao",
  "lat",
  "lvs",
  "lit",
  "ltz",
  "mkd",
  "mlt",
  "mon",
  "mri",
  "nso",
  "oci",
  "ori",
  "orm",
  "prs",
  "san",
  "slk",
  "slv",
  "smo",
  "sna",
  "snd",
  "sot",
  "tah",
  "tat",
  "tgk",
  "tir",
  "ton",
  "tsn",
  "tuk",
  "uig",
  "vol",
  "wol",
  "xho",
  "ydd",
  "aka",
  "bam",
  "bis",
  "bod",
  "che",
  "chv",
  "dzo",
  "ewe",
  "kab",
  "lug",
  "oss",
  "ssw",
  "ven",
  "war",
  "nde",
  "nbl",
  "pam",
  "hil",
  "bcl",
  "min",
  "ace",
  "bug",
  "ban",
  "bjn",
  "mak",
  "sas",
  "tet",
  "cha",
  "niu",
  "tvl",
  "gil",
  "mah",
  "pau",
  "wls",
  "rar",
  "hif",
] as const

export type LangCode = (typeof LANG_CODES)[number]

export const langCodeSchema = z.enum(LANG_CODES)

/** English language names for LLM prompt {{targetLanguage}} (as in Read Frog translate-text.ts). */
export const LANG_CODE_TO_EN_NAME = {
  "eng": "English",
  "cmn": "Simplified Mandarin Chinese",
  "cmn-Hant": "Traditional Mandarin Chinese",
  "yue": "Cantonese",
  "spa": "Spanish",
  "rus": "Russian",
  "arb": "Standard Arabic",
  "ben": "Bengali",
  "hin": "Hindi",
  "por": "Portuguese",
  "ind": "Indonesian",
  "jpn": "Japanese",
  "fra": "French",
  "deu": "German",
  "jav": "Javanese (Javanese)",
  "kor": "Korean",
  "tel": "Telugu",
  "vie": "Vietnamese",
  "mar": "Marathi",
  "ita": "Italian",
  "tam": "Tamil",
  "tur": "Turkish",
  "urd": "Urdu",
  "guj": "Gujarati",
  "pol": "Polish",
  "ukr": "Ukrainian",
  "kan": "Kannada",
  "mai": "Maithili",
  "mal": "Malayalam",
  "pes": "Iranian Persian",
  "mya": "Burmese",
  "swh": "Swahili (individual language)",
  "sun": "Sundanese",
  "ron": "Romanian",
  "pan": "Panjabi",
  "bho": "Bhojpuri",
  "amh": "Amharic",
  "hau": "Hausa",
  "fuv": "Nigerian Fulfulde",
  "bos": "Bosnian (Cyrillic)",
  "hrv": "Croatian",
  "nld": "Dutch",
  "srp": "Serbian (Cyrillic)",
  "tha": "Thai",
  "ckb": "Central Kurdish",
  "yor": "Yoruba",
  "uzn": "Northern Uzbek (Cyrillic)",
  "zlm": "Malay (individual language) (Arabic)",
  "ibo": "Igbo",
  "npi": "Nepali (individual language)",
  "ceb": "Cebuano",
  "skr": "Saraiki",
  "tgl": "Tagalog",
  "hun": "Hungarian",
  "azj": "North Azerbaijani (Cyrillic)",
  "sin": "Sinhala",
  "koi": "Komi-Permyak",
  "ell": "Modern Greek (1453-)",
  "ces": "Czech",
  "mag": "Magahi",
  "run": "Rundi",
  "bel": "Belarusian",
  "plt": "Plateau Malagasy",
  "qug": "Chimborazo Highland Quichua",
  "mad": "Madurese",
  "nya": "Nyanja",
  "zyb": "Yongbei Zhuang",
  "pbu": "Northern Pashto",
  "kin": "Kinyarwanda",
  "zul": "Zulu",
  "bul": "Bulgarian",
  "swe": "Swedish",
  "lin": "Lingala",
  "som": "Somali",
  "hms": "Southern Qiandong Miao",
  "hnj": "Hmong Njua",
  "ilo": "Iloko",
  "kaz": "Kazakh",
  "heb": "Hebrew",
  "nob": "Norwegian Bokmål",
  "nno": "Norwegian Nynorsk",
  "afr": "Afrikaans",
  "sqi": "Albanian",
  "asm": "Assamese",
  "eus": "Basque",
  "bre": "Breton",
  "cat": "Catalan",
  "cos": "Corsican",
  "cym": "Welsh",
  "dan": "Danish",
  "div": "Divehi",
  "epo": "Esperanto",
  "ekk": "Estonian",
  "fao": "Faroese",
  "fij": "Fijian",
  "fin": "Finnish",
  "fry": "Western Frisian",
  "gla": "Scottish Gaelic",
  "gle": "Irish",
  "glg": "Galician",
  "grn": "Guarani",
  "hat": "Haitian Creole",
  "haw": "Hawaiian",
  "hye": "Armenian",
  "ido": "Ido",
  "ina": "Interlingua",
  "isl": "Icelandic",
  "kat": "Georgian",
  "khm": "Khmer",
  "kir": "Kyrgyz",
  "lao": "Lao",
  "lat": "Latin",
  "lvs": "Latvian",
  "lit": "Lithuanian",
  "ltz": "Luxembourgish",
  "mkd": "Macedonian",
  "mlt": "Maltese",
  "mon": "Mongolian",
  "mri": "Maori",
  "nso": "Northern Sotho",
  "oci": "Occitan",
  "ori": "Odia",
  "orm": "Oromo",
  "prs": "Dari",
  "san": "Sanskrit",
  "slk": "Slovak",
  "slv": "Slovenian",
  "smo": "Samoan",
  "sna": "Shona",
  "snd": "Sindhi",
  "sot": "Southern Sotho",
  "tah": "Tahitian",
  "tat": "Tatar",
  "tgk": "Tajik",
  "tir": "Tigrinya",
  "ton": "Tongan",
  "tsn": "Tswana",
  "tuk": "Turkmen",
  "uig": "Uyghur",
  "vol": "Volapük",
  "wol": "Wolof",
  "xho": "Xhosa",
  "ydd": "Eastern Yiddish",
  "aka": "Akan",
  "bam": "Bambara",
  "bis": "Bislama",
  "bod": "Tibetan",
  "che": "Chechen",
  "chv": "Chuvash",
  "dzo": "Dzongkha",
  "ewe": "Ewe",
  "kab": "Kabyle",
  "lug": "Ganda",
  "oss": "Ossetian",
  "ssw": "Swati",
  "ven": "Venda",
  "war": "Waray",
  "nde": "North Ndebele",
  "nbl": "South Ndebele",
  "pam": "Pampanga",
  "hil": "Hiligaynon",
  "bcl": "Central Bikol",
  "min": "Minangkabau",
  "ace": "Acehnese",
  "bug": "Buginese",
  "ban": "Balinese",
  "bjn": "Banjar",
  "mak": "Makasar",
  "sas": "Sasak",
  "tet": "Tetum",
  "cha": "Chamorro",
  "niu": "Niuean",
  "tvl": "Tuvaluan",
  "gil": "Gilbertese",
  "mah": "Marshallese",
  "pau": "Palauan",
  "wls": "Wallisian",
  "rar": "Rarotongan",
  "hif": "Fiji Hindi",
} as const satisfies Record<LangCode, string>

/** English UI display names; the legacy export name is retained for compatibility. */
export const LANG_CODE_TO_ZH_NAME = {
  "eng": "English",
  "cmn": "Simplified Mandarin Chinese",
  "cmn-Hant": "Traditional Mandarin Chinese",
  "yue": "Cantonese",
  "spa": "Spanish",
  "rus": "Russian",
  "arb": "Standard Arabic",
  "ben": "Bengali",
  "hin": "Hindi",
  "por": "Portuguese",
  "ind": "Indonesian",
  "jpn": "Japanese",
  "fra": "French",
  "deu": "German",
  "jav": "Javanese (Javanese)",
  "kor": "Korean",
  "tel": "Telugu",
  "vie": "Vietnamese",
  "mar": "Marathi",
  "ita": "Italian",
  "tam": "Tamil",
  "tur": "Turkish",
  "urd": "Urdu",
  "guj": "Gujarati",
  "pol": "Polish",
  "ukr": "Ukrainian",
  "kan": "Kannada",
  "mai": "Maithili",
  "mal": "Malayalam",
  "pes": "Iranian Persian",
  "mya": "Burmese",
  "swh": "Swahili (individual language)",
  "sun": "Sundanese",
  "ron": "Romanian",
  "pan": "Panjabi",
  "bho": "Bhojpuri",
  "amh": "Amharic",
  "hau": "Hausa",
  "fuv": "Nigerian Fulfulde",
  "bos": "Bosnian (Cyrillic)",
  "hrv": "Croatian",
  "nld": "Dutch",
  "srp": "Serbian (Cyrillic)",
  "tha": "Thai",
  "ckb": "Central Kurdish",
  "yor": "Yoruba",
  "uzn": "Northern Uzbek (Cyrillic)",
  "zlm": "Malay (individual language) (Arabic)",
  "ibo": "Igbo",
  "npi": "Nepali (individual language)",
  "ceb": "Cebuano",
  "skr": "Saraiki",
  "tgl": "Tagalog",
  "hun": "Hungarian",
  "azj": "North Azerbaijani (Cyrillic)",
  "sin": "Sinhala",
  "koi": "Komi-Permyak",
  "ell": "Modern Greek (1453-)",
  "ces": "Czech",
  "mag": "Magahi",
  "run": "Rundi",
  "bel": "Belarusian",
  "plt": "Plateau Malagasy",
  "qug": "Chimborazo Highland Quichua",
  "mad": "Madurese",
  "nya": "Nyanja",
  "zyb": "Yongbei Zhuang",
  "pbu": "Northern Pashto",
  "kin": "Kinyarwanda",
  "zul": "Zulu",
  "bul": "Bulgarian",
  "swe": "Swedish",
  "lin": "Lingala",
  "som": "Somali",
  "hms": "Southern Qiandong Miao",
  "hnj": "Hmong Njua",
  "ilo": "Iloko",
  "kaz": "Kazakh",
  "heb": "Hebrew",
  "nob": "Norwegian Bokmål",
  "nno": "Norwegian Nynorsk",
  "afr": "Afrikaans",
  "sqi": "Albanian",
  "asm": "Assamese",
  "eus": "Basque",
  "bre": "Breton",
  "cat": "Catalan",
  "cos": "Corsican",
  "cym": "Welsh",
  "dan": "Danish",
  "div": "Divehi",
  "epo": "Esperanto",
  "ekk": "Estonian",
  "fao": "Faroese",
  "fij": "Fijian",
  "fin": "Finnish",
  "fry": "Western Frisian",
  "gla": "Scottish Gaelic",
  "gle": "Irish",
  "glg": "Galician",
  "grn": "Guarani",
  "hat": "Haitian Creole",
  "haw": "Hawaiian",
  "hye": "Armenian",
  "ido": "Ido",
  "ina": "Interlingua",
  "isl": "Icelandic",
  "kat": "Georgian",
  "khm": "Khmer",
  "kir": "Kyrgyz",
  "lao": "Lao",
  "lat": "Latin",
  "lvs": "Latvian",
  "lit": "Lithuanian",
  "ltz": "Luxembourgish",
  "mkd": "Macedonian",
  "mlt": "Maltese",
  "mon": "Mongolian",
  "mri": "Maori",
  "nso": "Northern Sotho",
  "oci": "Occitan",
  "ori": "Odia",
  "orm": "Oromo",
  "prs": "Dari",
  "san": "Sanskrit",
  "slk": "Slovak",
  "slv": "Slovenian",
  "smo": "Samoan",
  "sna": "Shona",
  "snd": "Sindhi",
  "sot": "Southern Sotho",
  "tah": "Tahitian",
  "tat": "Tatar",
  "tgk": "Tajik",
  "tir": "Tigrinya",
  "ton": "Tongan",
  "tsn": "Tswana",
  "tuk": "Turkmen",
  "uig": "Uyghur",
  "vol": "Volapük",
  "wol": "Wolof",
  "xho": "Xhosa",
  "ydd": "Eastern Yiddish",
  "aka": "Akan",
  "bam": "Bambara",
  "bis": "Bislama",
  "bod": "Tibetan",
  "che": "Chechen",
  "chv": "Chuvash",
  "dzo": "Dzongkha",
  "ewe": "Ewe",
  "kab": "Kabyle",
  "lug": "Ganda",
  "oss": "Ossetian",
  "ssw": "Swati",
  "ven": "Venda",
  "war": "Waray",
  "nde": "North Ndebele",
  "nbl": "South Ndebele",
  "pam": "Pampanga",
  "hil": "Hiligaynon",
  "bcl": "Central Bikol",
  "min": "Minangkabau",
  "ace": "Acehnese",
  "bug": "Buginese",
  "ban": "Balinese",
  "bjn": "Banjar",
  "mak": "Makasar",
  "sas": "Sasak",
  "tet": "Tetum",
  "cha": "Chamorro",
  "niu": "Niuean",
  "tvl": "Tuvaluan",
  "gil": "Gilbertese",
  "mah": "Marshallese",
  "pau": "Palauan",
  "wls": "Wallisian",
  "rar": "Rarotongan",
  "hif": "Fiji Hindi",
} as const satisfies Record<LangCode, string>

/** Native language names, displayed in their own languages. */
export const LANG_CODE_TO_LOCALE_NAME = {
  "eng": "English",
  "cmn": "简体中文",
  "cmn-Hant": "繁體中文",
  "yue": "粵語",
  "spa": "Español",
  "rus": "Русский",
  "arb": "العربية",
  "ben": "বাংলা",
  "hin": "हिन्दी",
  "por": "Português",
  "ind": "Bahasa Indonesia",
  "jpn": "日本語",
  "fra": "Français",
  "deu": "Deutsch",
  "jav": "Basa Jawa",
  "kor": "한국어",
  "tel": "తెలుగు",
  "vie": "Tiếng Việt",
  "mar": "मराठी",
  "ita": "Italiano",
  "tam": "தமிழ்",
  "tur": "Türkçe",
  "urd": "اردو",
  "guj": "ગુજરાતી",
  "pol": "Polski",
  "ukr": "Українська",
  "kan": "ಕನ್ನಡ",
  "mai": "मैथिली",
  "mal": "മലയാളം",
  "pes": "فارسی",
  "mya": "မြန်မာစာ",
  "swh": "Kiswahili",
  "sun": "Basa Sunda",
  "ron": "Română",
  "pan": "ਪੰਜਾਬੀ",
  "bho": "भोजपुरी",
  "amh": "አማርኛ",
  "hau": "Hausa",
  "fuv": "Fulfulde",
  "bos": "Босански",
  "hrv": "Hrvatski",
  "nld": "Nederlands",
  "srp": "Српски",
  "tha": "ไทย",
  "ckb": "کوردیی ناوەندی",
  "yor": "Yorùbá",
  "uzn": "Ўзбекча",
  "zlm": "بهاس ملايو",
  "ibo": "Asụsụ Igbo",
  "npi": "नेपाली",
  "ceb": "Cebuano",
  "skr": "سرائیکی",
  "tgl": "Tagalog",
  "hun": "Magyar",
  "azj": "Азәрбајҹан дили",
  "sin": "සිංහල",
  "koi": "Перем Коми кыв",
  "ell": "Ελληνικά",
  "ces": "Čeština",
  "mag": "मगही",
  "run": "Ikirundi",
  "bel": "Беларуская",
  "plt": "Fiteny Malagasy",
  "qug": "Kichwa",
  "mad": "Madhurâ",
  "nya": "Chinyanja",
  "zyb": "Yongbei Bouxcuengh",
  "pbu": "پښتو",
  "kin": "Kinyarwanda",
  "zul": "isiZulu",
  "bul": "Български",
  "swe": "Svenska",
  "lin": "Lingála",
  "som": "Af Soomaali",
  "hms": "Hmongb Shuad",
  "hnj": "Hmong Njua",
  "ilo": "Ilokano",
  "kaz": "Қазақ тілі",
  "heb": "עברית",
  "nob": "Norsk bokmål",
  "nno": "Norsk nynorsk",
  "afr": "Afrikaans",
  "sqi": "Shqip",
  "asm": "অসমীয়া",
  "eus": "Euskara",
  "bre": "Brezhoneg",
  "cat": "Català",
  "cos": "Corsu",
  "cym": "Cymraeg",
  "dan": "Dansk",
  "div": "ދިވެހި",
  "epo": "Esperanto",
  "ekk": "Eesti",
  "fao": "Føroyskt",
  "fij": "Vosa Vakaviti",
  "fin": "Suomi",
  "fry": "Frysk",
  "gla": "Gàidhlig",
  "gle": "Gaeilge",
  "glg": "Galego",
  "grn": "Avañeʼẽ",
  "hat": "Kreyòl ayisyen",
  "haw": "ʻŌlelo Hawaiʻi",
  "hye": "Հایերен",
  "ido": "Ido",
  "ina": "Interlingua",
  "isl": "Íslenska",
  "kat": "ქართული",
  "khm": "ភាសាខ្មែរ",
  "kir": "Кыргызча",
  "lao": "ພາສາລາວ",
  "lat": "Latina",
  "lvs": "Latviešu",
  "lit": "Lietuvių",
  "ltz": "Lëtzebuergesch",
  "mkd": "Македонски",
  "mlt": "Malti",
  "mon": "Монгол",
  "mri": "Te Reo Māori",
  "nso": "Sesotho sa Leboa",
  "oci": "Occitan",
  "ori": "ଓଡ଼ିଆ",
  "orm": "Oromoo",
  "prs": "دری",
  "san": "संस्कृतम्",
  "slk": "Slovenčina",
  "slv": "Slovenščina",
  "smo": "Gagana Samoa",
  "sna": "chiShona",
  "snd": "سنڌي",
  "sot": "Sesotho",
  "tah": "Reo Tahiti",
  "tat": "Татарча",
  "tgk": "Тоҷикӣ",
  "tir": "ትግርኛ",
  "ton": "Lea fakatonga",
  "tsn": "Setswana",
  "tuk": "Türkmençe",
  "uig": "ئۇيغۇرچە",
  "vol": "Volapük",
  "wol": "Wolof",
  "xho": "isiXhosa",
  "ydd": "ייִדיש",
  "aka": "Akan",
  "bam": "Bamanankan",
  "bis": "Bislama",
  "bod": "བོད་སྐད",
  "che": "Нохчийн",
  "chv": "Чӑвашла",
  "dzo": "རྫོང་ཁ",
  "ewe": "Eʋegbe",
  "kab": "Taqbaylit",
  "lug": "Luganda",
  "oss": "Ирон",
  "ssw": "SiSwati",
  "ven": "Tshivenḓa",
  "war": "Winaray",
  "nde": "isiNdebele",
  "nbl": "isiNdebele seSewula",
  "pam": "Kapampangan",
  "hil": "Ilonggo",
  "bcl": "Bikol Sentral",
  "min": "Baso Minangkabau",
  "ace": "Bahsa Acèh",
  "bug": "Basa Ugi",
  "ban": "Basa Bali",
  "bjn": "Bahasa Banjar",
  "mak": "Basa Mangkasara",
  "sas": "Sasak",
  "tet": "Tetun",
  "cha": "Chamoru",
  "niu": "Vagahau Niuē",
  "tvl": "Te Gana Tuvalu",
  "gil": "Taetae ni Kiribati",
  "mah": "Kajin Majel",
  "pau": "A tekoi er a Belau",
  "wls": "Fakaʻuvea",
  "rar": "Māori Kūki ʻĀirani",
  "hif": "फ़िजी हिंदी",
} as const satisfies Record<LangCode, string>

/** ISO 639-3 → BCP-47 (used by Google and others); 38 codes have no two-letter equivalent. */
export const ISO6393_TO_6391 = {
  "eng": "en",
  "cmn": "zh",
  "cmn-Hant": "zh-TW",
  "yue": "zh",
  "spa": "es",
  "rus": "ru",
  "arb": "ar",
  "ben": "bn",
  "hin": "hi",
  "por": "pt",
  "ind": "id",
  "jpn": "ja",
  "fra": "fr",
  "deu": "de",
  "jav": "jv",
  "kor": "ko",
  "tel": "te",
  "vie": "vi",
  "mar": "mr",
  "ita": "it",
  "tam": "ta",
  "tur": "tr",
  "urd": "ur",
  "guj": "gu",
  "pol": "pl",
  "ukr": "uk",
  "kan": "kn",
  "mal": "ml",
  "pes": "fa",
  "mya": "my",
  "swh": "sw",
  "sun": "su",
  "ron": "ro",
  "pan": "pa",
  "amh": "am",
  "hau": "ha",
  "fuv": "ff",
  "bos": "bs",
  "hrv": "hr",
  "nld": "nl",
  "srp": "sr",
  "tha": "th",
  "ckb": "ku",
  "yor": "yo",
  "uzn": "uz",
  "zlm": "ms",
  "ibo": "ig",
  "npi": "ne",
  "tgl": "tl",
  "hun": "hu",
  "azj": "az",
  "sin": "si",
  "ell": "el",
  "ces": "cs",
  "bel": "be",
  "nya": "ny",
  "kin": "rw",
  "zul": "zu",
  "bul": "bg",
  "swe": "sv",
  "lin": "ln",
  "som": "so",
  "kaz": "kk",
  "heb": "he",
  "nob": "nb",
  "nno": "nn",
  "afr": "af",
  "sqi": "sq",
  "asm": "as",
  "eus": "eu",
  "bre": "br",
  "cat": "ca",
  "cos": "co",
  "cym": "cy",
  "dan": "da",
  "div": "dv",
  "epo": "eo",
  "ekk": "et",
  "fao": "fo",
  "fij": "fj",
  "fin": "fi",
  "fry": "fy",
  "gla": "gd",
  "gle": "ga",
  "glg": "gl",
  "grn": "gn",
  "hat": "ht",
  "hye": "hy",
  "ido": "io",
  "ina": "ia",
  "isl": "is",
  "kat": "ka",
  "khm": "km",
  "kir": "ky",
  "lao": "lo",
  "lat": "la",
  "lvs": "lv",
  "lit": "lt",
  "ltz": "lb",
  "mkd": "mk",
  "mlt": "mt",
  "mon": "mn",
  "mri": "mi",
  "oci": "oc",
  "ori": "or",
  "orm": "om",
  "san": "sa",
  "slk": "sk",
  "slv": "sl",
  "smo": "sm",
  "sna": "sn",
  "snd": "sd",
  "sot": "st",
  "tah": "ty",
  "tat": "tt",
  "tgk": "tg",
  "tir": "ti",
  "ton": "to",
  "tsn": "tn",
  "tuk": "tk",
  "uig": "ug",
  "vol": "vo",
  "wol": "wo",
  "xho": "xh",
  "ydd": "yi",
  "aka": "ak",
  "bam": "bm",
  "bis": "bi",
  "bod": "bo",
  "che": "ce",
  "chv": "cv",
  "dzo": "dz",
  "ewe": "ee",
  "lug": "lg",
  "oss": "os",
  "ssw": "ss",
  "ven": "ve",
  "nde": "nd",
  "nbl": "nr",
  "cha": "ch",
  "mah": "mh",
} as const satisfies Partial<Record<LangCode, string>>

export const DEFAULT_LANG_CODE: LangCode = 'cmn'

export function isLangCode(value: string): value is LangCode {
  return (LANG_CODES as readonly string[]).includes(value)
}

/** Language name for prompts; pass through unknown codes from custom or older configs. */
export function englishName(code: string): string {
  return isLangCode(code) ? LANG_CODE_TO_EN_NAME[code] : code
}

/** Settings label: English name (native name), corresponding to Read Frog language-labels.ts getLanguageLabel. */
export function label(code: LangCode): string {
  const zh = LANG_CODE_TO_ZH_NAME[code]
  const local = LANG_CODE_TO_LOCALE_NAME[code]
  return zh === local ? zh : `${zh} (${local})`
}

/** For engines accepting BCP-47 targets (google-web); pass through ISO 639-3 when no two-letter code exists. */
const BCP47: Partial<Record<LangCode, string>> = ISO6393_TO_6391

/**
 * Override two-letter codes that lose language or script distinctions supported by the endpoint (three rounds of Codex #39; each verified):
 * - yue and cmn both map to zh, which produces Mandarin (observed yue: "巴士站喺邊"; zh: "公交车站在哪里").
 * - ckb (Sorani) and kmr (Kurmanji) both map to ku, which produces Kurmanji (ckb: Arabic-script "وێستگەی پاس"; ku: Latin-script "Rawestgeha").
 * - zlm is "Malay (individual language) (Arabic)"; ms produces Latin-script Malay (ms-Arab returned Jawi "دمان ڤرهنتين بس؟").
 *
 * Three other script distinctions are **unsupported by the endpoint** and remain unchanged (bs / bs-Cyrl, uz / uz-Cyrl, az / az-Cyrl returned identical Latin text):
 * bos "Bosnian (Cyrillic)", uzn "Northern Uzbek (Cyrillic)", azj "North Azerbaijani (Cyrillic)".
 * srp "Serbian (Cyrillic)" already works (sr always returns Cyrillic). LLMs are unaffected: the English names include the script.
 */
const BCP47_OVERRIDES: Partial<Record<LangCode, string>> = { yue: 'yue', ckb: 'ckb', zlm: 'ms-Arab' }

export function toBcp47(code: string): string {
  if (!isLangCode(code)) return code
  return BCP47_OVERRIDES[code] ?? BCP47[code] ?? code
}

/**
 * BCP-47 → ISO 639-3 for config v3→v4 migration. BCP-47 is case-insensitive (Codex #39).
 * Try exact reverse lookup (zh-TW → cmn-Hant), then matching region/script subtags within the same primary language
 * (zh-Hant-TW ∩ zh-TW → cmn-Hant). Traditional Chinese script or Hong Kong/Macau/Taiwan tags (zh-Hant, zh-HK, zh-MO) without a table entry
 * map to cmn-Hant (Codex #39, round 2: primary-language fallback alone silently changes Traditional to Simplified). Then fall back by primary language
 * (zh-CN → zh → cmn; cmn precedes yue in the table), or finally to Simplified Chinese.
 */
export function fromBcp47(tag: string): LangCode {
  if (isLangCode(tag)) return tag
  const wanted = tag.toLowerCase()
  const [primary = '', ...subtags] = wanted.split('-')
  const entries = (Object.entries(ISO6393_TO_6391) as [LangCode, string][]).map(([code, bcp]) => [code, bcp.toLowerCase().split('-')] as const)
  const exact = entries.find(([, parts]) => parts.join('-') === wanted)
  if (exact) return exact[0]
  const sameLanguage = entries.filter(([, parts]) => parts[0] === primary)
  const overlapping = sameLanguage.find(([, parts]) => parts.slice(1).some(part => subtags.includes(part)))
  if (overlapping) return overlapping[0]
  if (primary === 'zh' && subtags.some(part => TRADITIONAL_CHINESE_SUBTAGS.has(part))) return 'cmn-Hant'
  return sameLanguage[0]?.[0] ?? DEFAULT_LANG_CODE
}

/** Traditional Chinese script/region subtags, in lowercase. */
const TRADITIONAL_CHINESE_SUBTAGS = new Set(['hant', 'tw', 'hk', 'mo'])
