// The names a translated final gives its floats, by target: what babel's locale files say \figurename and \tablename
// are, read offline from the TeX Live image the finals are compiled in (texlive/texlive:latest), so that the layer
// labels a float as the final does (the table-groups brief, Problem 2: the layer kept "Table 2:" in English where the
// final printed the target's name). The final loads the target as babel's main language from its ini file, the first
// of the tags scripts.mjs babelTags tries that the tree holds (\babelprovide[import=<tag>,main]); the label is
// \figurename or \tablename, a tie and the number, then the class's separator — so only the name is the language's,
// and the number and the punctuation stay the original's.
//   node scripts/caption-names.mjs            writes src/pdf-reader/engine/caption-names.mjs
//   node scripts/caption-names.mjs --check    also compiles a probe per target in the image (XeLaTeX, babel imported as
//                                             the final imports it) and compares what TeX says the two names are
// Docker, the image pulled, no network. Every non-ASCII character is written as a \u escape.
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { babelTags } from '../src/pdf-reader/engine/scripts.mjs'
import { VERIFIED } from '../src/pdf-reader/engine/verified.mjs'

const IMAGE = 'texlive/texlive:latest'
const OUT = new URL('../src/pdf-reader/engine/caption-names.mjs', import.meta.url).pathname
/** the targets: the languages the reader typesets, and Traditional Chinese by the extension's own tag */
const TARGETS = [...new Set([...VERIFIED, 'zh-TW'])]
const sh = script => execFileSync('docker', ['run', '--rm', '--network', 'none', IMAGE, 'sh', '-c', script], { encoding: 'utf8', maxBuffer: 1 << 26 })
const image = execFileSync('docker', ['image', 'inspect', IMAGE, '--format', '{{.Id}}'], { encoding: 'utf8' }).trim()
const babelVersion = /\\def\\bbl@version\{([^}]+)\}/.exec(sh('cat "$(kpsewhich babel.sty)"'))?.[1] ?? '?'

/** an ini file's [captions] section, its keys → values */
const captionsOf = ini => {
  const out = {}
  let inCaptions = false
  for (const line of ini.split('\n')) {
    const head = /^\s*\[([^\]]+)\]/.exec(line)
    if (head) { inCaptions = head[1].trim() === 'captions'; continue }
    const kv = inCaptions && /^\s*([A-Za-z.]+)\s*=\s*(.*?)\s*$/.exec(line)
    if (kv) out[kv[1]] = kv[2]
  }
  return out
}
const asciiOnly = s => [...s].map(c => (c.codePointAt(0) < 0x80 ? c : `\\u${c.codePointAt(0).toString(16).padStart(4, '0')}`)).join('')

const names = {}
for (const lang of TARGETS) {
  const tags = babelTags(lang)
  const found = sh(`${tags.map(t => `f=$(kpsewhich babel-${t}.ini); [ -n "$f" ] && echo "${t} $f"`).join('; ')}; true`).trim().split('\n').filter(Boolean)
  if (!found.length) throw new Error(`${lang}: no babel-<tag>.ini for ${tags.join(', ')}`)
  const [tag, file] = found[0].split(' ')
  if (names[tag]) continue
  const c = captionsOf(sh(`cat ${file}`))
  if (!c.figure || !c.table) throw new Error(`${lang}: ${file} names no figure or table`)
  names[tag] = { figure: c.figure, table: c.table }
  console.log(`${lang} → babel-${tag}.ini: figure ${JSON.stringify(c.figure)}, table ${JSON.stringify(c.table)}`)
}

if (process.argv.includes('--check')) {
  // what TeX itself says, under XeLaTeX and babel as the final loads the target (scripts.mjs babel())
  const dir = mkdtempSync(join(tmpdir(), 'axt-captions-'))
  try {
    for (const tag of Object.keys(names)) {
      writeFileSync(join(dir, `${tag}.tex`), `\\documentclass{article}\n\\usepackage[safe=none]{babel}\n\\babelprovide[import=${tag},main]{axttarget}\n\\begin{document}\n\\typeout{AXT-CAPTIONS \\figurename|\\tablename|}\n\\end{document}\n`)
      execFileSync('docker', ['run', '--rm', '--network', 'none', '-v', `${dir}:/work`, '-w', '/work', IMAGE, 'xelatex', '-interaction=nonstopmode', `${tag}.tex`], { stdio: 'ignore' })
      // (babel wraps each name in its language's guard, \bbl@ensure@<language>{…}: the name is inside)
      const inner = x => (/^\\bbl@ensure@[A-Za-z@]+ ?\{(.*)\}$/.exec(x.trim())?.[1] ?? x.trim())
      const said = /AXT-CAPTIONS (.*?)\|(.*?)\|/.exec(readFileSync(join(dir, `${tag}.log`), 'utf8'))
      const ok = said && inner(said[1]) === names[tag].figure && inner(said[2]) === names[tag].table
      console.log(`${ok ? 'ok  ' : 'FAIL'} ${tag}: TeX says ${said ? `${JSON.stringify(inner(said[1]))}, ${JSON.stringify(inner(said[2]))}` : 'nothing'}`)
      if (!ok) process.exitCode = 1
    }
  } finally { rmSync(dir, { recursive: true, force: true }) }
}

const rows = Object.entries(names).map(([tag, n]) => `  '${tag}': { figure: '${asciiOnly(n.figure)}', table: '${asciiOnly(n.table)}' },`).join('\n')
writeFileSync(OUT, `// Generated by scripts/caption-names.mjs: do not edit. From TeX Live's babel locale files (babel ${babelVersion}) in
// ${IMAGE} (${image}):
// the [captions] figure and table of the ini file the final imports for each target.
// The names a translated final gives its floats (\\figurename, \\tablename): the layer labels a float with them, as the
// final does, the number and the punctuation the original's (the table-groups brief, Problem 2).

/** by babel's tag: each float's name as babel's [captions] gives it */
export const CAPTION_NAMES = {
${rows}
}

/** the names a final into \`lang\` gives a figure and a table: the first of the tags scripts.mjs babelTags tries that babel
 *  has a file for, as the final's \\babelprovide takes it; null for a language no file names */
export function captionNames(lang) {
  const l = new Intl.Locale(lang)
  for (const tag of [lang, \`\${l.language}-\${l.maximize().script}\`, l.language]) if (Object.hasOwn(CAPTION_NAMES, tag)) return CAPTION_NAMES[tag]
  return null
}
`)
console.log(`written: ${OUT}`)
