# The display switch's two letters as outlines (the reader's design, §6.2): A and U+6587 (wen, "text") of Noto Sans SC (SIL OFL 1.1) at
# weight 350, the face's DemiLight, each centred by its ink on the switch's 24 × 18 pane, A 8 px high and U+6587 9 px (a CJK
# glyph looks smaller than a Latin capital of its height); U+6587 narrowed across to 0.8 of its width, the weight that takes
# from its verticals given back by a stroke of 0.16 px round its outline (icons.tsx WEN_GAIN). Outlines, so that every
# system draws the same shapes. Prints display-glyphs.ts:
#   python3 scripts/pdf-reader-glyphs.py <NotoSansSC-VariableFont_wght.ttf> > src/pdf-reader/ui/display-glyphs.ts
# Needs fontTools (pip install fonttools); the font is Google Fonts' Noto Sans SC, the variable face.
import sys
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

font = instantiateVariableFont(TTFont(sys.argv[1]), {'wght': 350})
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()


def outline(ch, height, narrow=1.0, cx=12, cy=9):
    """a glyph's outline, `height` px high, scaled across by `narrow`, its ink centred on (cx, cy), y down"""
    rec = DecomposingRecordingPen(glyphs)
    glyphs[cmap[ord(ch)]].draw(rec)
    bounds = BoundsPen(glyphs)
    rec.replay(bounds)
    x0, y0, x1, y1 = bounds.bounds
    s = height / (y1 - y0)
    pen = SVGPathPen(None, ntos=lambda v: ('%.2f' % v).rstrip('0').rstrip('.'))
    rec.replay(TransformPen(pen, (s * narrow, 0, 0, -s, cx - s * narrow * (x0 + x1) / 2, cy + s * (y0 + y1) / 2)))
    return pen.getCommands()


print("// Generated by scripts/pdf-reader-glyphs.py from Noto Sans SC (SIL OFL 1.1, docs/THIRD_PARTY.md): the display")
print("// switch's letters as outlines on its 24 × 18 pane (the reader's design, §6.2). Not edited by hand: run the script")
print(f"export const GLYPH_A = '{outline('A', 8)}'")
print(f"export const GLYPH_WEN = '{outline(chr(0x6587), 9, 0.8)}'")
